// design-sync barrel entry (generated by hand, not by the converter).
// Re-exports the curated ~130-component set for the claude.ai/design sync,
// plus DsProvider, the context wrapper every preview mounts inside.
//
// Runs the theme store's module-level side effect (applies persisted
// accent/theme CSS custom properties to <html>) the same way src/App.tsx does.
import "@/stores/themeStore";

import type { ReactNode } from "react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { MemoryRouter } from "react-router-dom";
import { StationProvider } from "@/components/station-ui/StationProvider";
import { HomeLocationProvider } from "@/components/home/HomeLocationProvider";

// -- ui/ ---------------------------------------------------------------
export { AccessibleDialog } from "@/components/ui/AccessibleDialog";
export { Badge } from "@/components/ui/Badge";
export { Card } from "@/components/ui/Card";
export { CommandPalette } from "@/components/ui/CommandPalette";
export { ConfirmDialog } from "@/components/ui/ConfirmDialog";
export { ConnectivityBadge } from "@/components/ui/ConnectivityBadge";
export { DataFreshnessIndicator } from "@/components/ui/DataFreshnessIndicator";
export { DataSourceError } from "@/components/ui/DataSourceError";
export { DetailModal } from "@/components/ui/DetailModal";
export { GlossaryTooltip } from "@/components/ui/GlossaryTooltip";
export { HealthStatusIndicator } from "@/components/ui/HealthStatusIndicator";
export { HelpModal } from "@/components/ui/HelpModal";
export { ImageCropDialog } from "@/components/ui/ImageCropDialog";
export { ImageUploadButton } from "@/components/ui/ImageUploadButton";
export { LoadingSpinner } from "@/components/ui/LoadingSpinner";
export { OfflineIndicator } from "@/components/ui/OfflineIndicator";
export { OnboardingTour } from "@/components/ui/OnboardingTour";
export { Pagination } from "@/components/ui/Pagination";
export { PanelCard } from "@/components/ui/PanelCard";
export { ProgressBar } from "@/components/ui/ProgressBar";
export { PullToRefreshIndicator } from "@/components/ui/PullToRefreshIndicator";
export { PWAInstallPrompt } from "@/components/ui/PWAInstallPrompt";
export { PWAUpdatePrompt } from "@/components/ui/PWAUpdatePrompt";
export { default as ReferencePanel } from "@/components/ui/ReferencePanel";
export { SectionHeader } from "@/components/ui/SectionHeader";
export { ShareModal } from "@/components/ui/ShareModal";
export { ShortcutsHelpModal } from "@/components/ui/ShortcutsHelpModal";
export { SyncStatusIndicator } from "@/components/ui/SyncStatusIndicator";
export { TimeDisplay } from "@/components/ui/TimeDisplay";
export { ToggleSwitch } from "@/components/ui/ToggleSwitch";
export { Tooltip } from "@/components/ui/Tooltip";
export { UndoToast } from "@/components/ui/UndoToast";
export { UpgradePrompt } from "@/components/ui/UpgradePrompt";

// -- station-ui/ ---------------------------------------------------------
export { Button, IconButton, ActionLink } from "@/components/station-ui/Actions";
export { KeyValueList, Table, Avatar } from "@/components/station-ui/DataDisplay";
export {
  Badge as StationBadge,
  ProvenanceBadge,
  Notice,
  EmptyState,
  Skeleton,
} from "@/components/station-ui/Feedback";
export {
  Field,
  TextField,
  SelectField,
  TextAreaField,
  Checkbox,
  Switch,
  ChoiceGroup,
  ImagePicker,
} from "@/components/station-ui/Fields";
export {
  Stack,
  Inline,
  Grid,
  Surface,
  Divider,
  PageHeader,
  Section,
  ActionBar,
  Disclosure,
} from "@/components/station-ui/Layout";
export { SectionNav, Tabs } from "@/components/station-ui/Navigation";
export { Dialog as StationDialog } from "@/components/station-ui/Overlays";
export {
  EquipmentGlyph,
  EquipmentTile,
  PortButton,
  ConnectionPreview,
  SetupStatus,
  ReorderControls,
} from "@/components/station-ui/Station";
export { StationProvider } from "@/components/station-ui/StationProvider";

// -- HamClock wall chrome -------------------------------------------------
export { HamClockTile } from "@/components/map/hamclock/wall/HamClockTile";
export { HamClockRail } from "@/components/map/hamclock/wall/HamClockRail";
export { HamClockWallHeader } from "@/components/map/hamclock/wall/HamClockWallHeader";
export { HamClockPager } from "@/components/map/hamclock/wall/HamClockPager";
export { WallStatus } from "@/components/map/hamclock/wall/WallStatus";
export { HamClockWallControls } from "@/components/map/hamclock/wall/HamClockWallControls";

// -- HamClock wall tiles ---------------------------------------------------
export { ActivationsTile } from "@/components/map/hamclock/wall/tiles/ActivationsTile";
export { AlertsTile } from "@/components/map/hamclock/wall/tiles/AlertsTile";
export { BandActivityTile } from "@/components/map/hamclock/wall/tiles/BandActivityTile";
export { BestBandTile } from "@/components/map/hamclock/wall/tiles/BestBandTile";
export { ClusterTile } from "@/components/map/hamclock/wall/tiles/ClusterTile";
export { DxTargetTile } from "@/components/map/hamclock/wall/tiles/DxTargetTile";
export { EmcommTile } from "@/components/map/hamclock/wall/tiles/EmcommTile";
export { ForecastMatrixTile } from "@/components/map/hamclock/wall/tiles/ForecastMatrixTile";
export { GreyLineTile } from "@/components/map/hamclock/wall/tiles/GreyLineTile";
export { MoonTile } from "@/components/map/hamclock/wall/tiles/MoonTile";
export { MufTile } from "@/components/map/hamclock/wall/tiles/MufTile";
export { PskStationTile } from "@/components/map/hamclock/wall/tiles/PskStationTile";
export { RecentContactsTile } from "@/components/map/hamclock/wall/tiles/RecentContactsTile";
export { ReliabilityTile } from "@/components/map/hamclock/wall/tiles/ReliabilityTile";
export { SdrDecodesTile } from "@/components/map/hamclock/wall/tiles/SdrDecodesTile";
export { SdrScopeTile } from "@/components/map/hamclock/wall/tiles/SdrScopeTile";
export { SolarWindTile } from "@/components/map/hamclock/wall/tiles/SolarWindTile";
export { SpaceWxTile } from "@/components/map/hamclock/wall/tiles/SpaceWxTile";
export { SunTile } from "@/components/map/hamclock/wall/tiles/SunTile";
export { WeatherTile } from "@/components/map/hamclock/wall/tiles/WeatherTile";
export { WsjtxTile } from "@/components/map/hamclock/wall/tiles/WsjtxTile";
export { XrayTile } from "@/components/map/hamclock/wall/tiles/XrayTile";

// -- solar/ ---------------------------------------------------------------
export { MetricCard } from "@/components/solar/MetricCard";
export { BandRow } from "@/components/solar/BandRow";
export { BandConditions } from "@/components/solar/BandConditions";
export { PrimaryMetrics } from "@/components/solar/PrimaryMetrics";
export { PropagationIndex } from "@/components/solar/PropagationIndex";
export { SolarImageCard } from "@/components/solar/SolarImageCard";
export { SolarOutlookBars } from "@/components/solar/SolarOutlookBars";
export { SolarMiniChart } from "@/components/solar/SolarMiniChart";
export { SolarForecastPanel } from "@/components/solar/SolarForecastPanel";
export { SolarDisclosure } from "@/components/solar/SolarDisclosure";
export { SolarBriefingNotice } from "@/components/solar/SolarBriefingNotice";
export { SolarOperatingActions } from "@/components/solar/SolarOperatingActions";

// -- home/ ------------------------------------------------------------------
export { HomeBandsLadder } from "@/components/home/HomeBandsLadder";
export { HomeForecastStrip } from "@/components/home/HomeForecastStrip";
export { HomeDaylight } from "@/components/home/HomeDaylight";
export { HomeStatus } from "@/components/home/HomeStatus";
export { HomeSession } from "@/components/home/HomeSession";
export { HomeStation } from "@/components/home/HomeStation";
export { HomeWeather } from "@/components/home/HomeWeather";
export { HomeSolar } from "@/components/home/HomeSolar";
export { HomeActivity } from "@/components/home/HomeActivity";
export { HomeBriefing } from "@/components/home/HomeBriefing";

// -- shack/ -----------------------------------------------------------------
export { EquipmentCard } from "@/components/shack/EquipmentCard";
export { EquipmentCardSm } from "@/components/shack/EquipmentCardSm";
export { EquipmentCardMd } from "@/components/shack/EquipmentCardMd";
export { EquipmentHeroCard } from "@/components/shack/EquipmentHeroCard";
export { BandCapabilityStrip } from "@/components/shack/BandCapabilityStrip";
export { FeedlineLossSparkline } from "@/components/shack/FeedlineLossSparkline";
export { EquipmentSection } from "@/components/shack/EquipmentSection";

// -- dx/ + layout/ ------------------------------------------------------------
export { SpotRow } from "@/components/dx/DXSpotList/SpotRow";
export { BandActivityBar } from "@/components/dx/BandActivityBar";
export { PredictionsCard } from "@/components/dx/PredictionsCard";
export { FloatingPanel } from "@/components/layout/FloatingPanel";

// -- provider ---------------------------------------------------------------
/**
 * Wraps every preview with the context PROPULSE components read at render
 * time: TanStack Query (retries off so previews don't hang on failed
 * fetches), a router (react-router hooks used throughout), the station-ui
 * theme/token provider, and the home-location context consumed by the
 * Home* widgets.
 */
export function DsProvider({ children }: { children: ReactNode }) {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: { retry: false, refetchOnWindowFocus: false },
      mutations: { retry: false },
    },
  });
  return (
    <QueryClientProvider client={queryClient}>
      <MemoryRouter initialEntries={["/"]}>
        <StationProvider>
          <HomeLocationProvider>{children}</HomeLocationProvider>
        </StationProvider>
      </MemoryRouter>
    </QueryClientProvider>
  );
}
