/**
 * Editable social links section.
 * Displays links as compact pills in read mode; shows full form in edit mode.
 */

import { useState } from "react";
import { useProfileStore } from "@/stores/profileStore";
import type { SocialLink, SocialLinkType } from "@/types/user";

const LINK_TYPES: {
  type: SocialLinkType;
  label: string;
  placeholder: string;
}[] = [
  { type: "qrz", label: "QRZ", placeholder: "https://www.qrz.com/db/..." },
  {
    type: "hamqth",
    label: "HamQTH",
    placeholder: "https://www.hamqth.com/...",
  },
  { type: "website", label: "Website", placeholder: "https://..." },
  {
    type: "twitter",
    label: "Twitter/X",
    placeholder: "https://twitter.com/...",
  },
  {
    type: "mastodon",
    label: "Mastodon",
    placeholder: "https://mastodon.radio/...",
  },
];

export function SocialLinksSection() {
  const socialLinks = useProfileStore((s) => s.socialLinks);
  const setSocialLinks = useProfileStore((s) => s.setSocialLinks);
  const [isEditing, setIsEditing] = useState(false);
  const [draft, setDraft] = useState<SocialLink[]>(socialLinks);
  const [validationErrors, setValidationErrors] = useState<Map<string, string>>(
    new Map(),
  );

  const handleEdit = () => {
    setDraft([...socialLinks]);
    setIsEditing(true);
  };

  const handleSave = () => {
    const filtered = draft.filter((l) => l.url.trim());
    const errors = new Map<string, string>();
    for (const link of filtered) {
      const url = link.url.trim();
      if (url && !url.startsWith("http://") && !url.startsWith("https://")) {
        errors.set(link.type, "URL must start with http:// or https://");
      }
    }
    if (errors.size > 0) {
      setValidationErrors(errors);
      return;
    }
    setValidationErrors(new Map());
    setSocialLinks(filtered);
    setIsEditing(false);
  };

  const handleCancel = () => {
    setDraft(socialLinks);
    setValidationErrors(new Map());
    setIsEditing(false);
  };

  const updateLink = (type: SocialLinkType, url: string) => {
    setDraft((prev) => {
      const existing = prev.find((l) => l.type === type);
      if (existing) {
        return prev.map((l) => (l.type === type ? { ...l, url } : l));
      }
      return [...prev, { type, url }];
    });
  };

  const getLinkUrl = (type: SocialLinkType): string => {
    return (
      (isEditing ? draft : socialLinks).find((l) => l.type === type)?.url ?? ""
    );
  };

  const isAutoGenerated = (type: SocialLinkType): boolean => {
    return socialLinks.find((l) => l.type === type)?.autoGenerated ?? false;
  };

  if (!isEditing) {
    const visibleLinks = socialLinks.filter((l) => l.url);
    return (
      <div>
        <div className="flex items-center justify-between mb-2">
          <h3 className="text-sm font-semibold text-gray-400 uppercase tracking-wider">
            Links
          </h3>
          <button
            onClick={handleEdit}
            className="text-xs text-plasma-orange hover:text-plasma-orange/80"
          >
            Edit
          </button>
        </div>
        {visibleLinks.length > 0 ? (
          <div className="flex flex-wrap gap-2">
            {visibleLinks.map((link) => {
              const meta = LINK_TYPES.find((t) => t.type === link.type);
              return (
                <a
                  key={link.type}
                  href={link.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  aria-label={`${meta?.label ?? link.type}${link.autoGenerated ? " (auto-generated)" : ""} link`}
                  className="px-2 py-1 rounded text-xs font-medium bg-white/5 border border-white/10 text-gray-300 hover:text-plasma-orange hover:border-plasma-orange/30 transition-colors"
                >
                  {meta?.label ?? link.type}
                  {link.autoGenerated && (
                    <span className="ml-1 text-gray-500">(auto)</span>
                  )}
                </a>
              );
            })}
          </div>
        ) : (
          <p className="text-sm text-gray-500 italic">No links added.</p>
        )}
      </div>
    );
  }

  return (
    <div>
      <h3 className="text-sm font-semibold text-gray-400 uppercase tracking-wider mb-3">
        Links
      </h3>
      <div className="space-y-3">
        {LINK_TYPES.map((meta) => (
          <div key={meta.type}>
            <label className="block text-xs font-medium text-gray-400 mb-1">
              {meta.label}
              {isAutoGenerated(meta.type) && (
                <span className="ml-1 text-gray-500">(auto-generated)</span>
              )}
            </label>
            <input
              type="url"
              value={getLinkUrl(meta.type)}
              onChange={(e) => updateLink(meta.type, e.target.value)}
              placeholder={meta.placeholder}
              className="w-full bg-void-black border border-white/10 rounded-lg px-3 py-2 text-sm text-gray-200 focus:border-plasma-orange/50 focus:outline-none"
            />
            {validationErrors.get(meta.type) && (
              <p className="mt-1 text-xs text-alert-red">
                {validationErrors.get(meta.type)}
              </p>
            )}
          </div>
        ))}
      </div>
      <div className="flex gap-2 mt-3">
        <button
          onClick={handleCancel}
          className="px-3 py-1.5 text-xs rounded-lg bg-white/5 border border-white/10 text-gray-300 hover:text-white"
        >
          Cancel
        </button>
        <button
          onClick={handleSave}
          className="px-3 py-1.5 text-xs rounded-lg bg-plasma-orange text-white hover:bg-plasma-orange/80 font-medium"
        >
          Save Links
        </button>
      </div>
    </div>
  );
}
