/**
 * Editable social links section.
 * Displays links as compact pills in read mode; shows full form in edit mode.
 *
 * Draft state is controlled by ProfilePage so edits survive tab changes (#354).
 */

import { useProfileStore } from "@/stores/profileStore";
import type { SocialLink, SocialLinkType } from "@/types/user";

const LINK_TYPES: {
  type: SocialLinkType;
  label: string;
  placeholder: string;
}[] = [
  { type: "qrz", label: "QRZ", placeholder: "https://www.qrz.com/db/..." },
  {
    type: "hamqth",
    label: "HamQTH",
    placeholder: "https://www.hamqth.com/...",
  },
  { type: "website", label: "Website", placeholder: "https://..." },
  {
    type: "twitter",
    label: "Twitter/X",
    placeholder: "https://twitter.com/...",
  },
  {
    type: "mastodon",
    label: "Mastodon",
    placeholder: "https://mastodon.radio/...",
  },
];

export interface SocialLinksDraftState {
  draft: SocialLink[];
  isEditing: boolean;
  validationErrors: Record<SocialLinkType, string | undefined>;
}

// eslint-disable-next-line react-refresh/only-export-components -- draft helpers shared with ProfilePage (#354)
export function createSocialLinksDraftState(
  socialLinks: SocialLink[],
  isEditing = false,
): SocialLinksDraftState {
  return {
    draft: [...socialLinks],
    isEditing,
    validationErrors: {
      qrz: undefined,
      hamqth: undefined,
      website: undefined,
      twitter: undefined,
      mastodon: undefined,
    },
  };
}

function normalizeSocialLinks(links: SocialLink[]): SocialLink[] {
  return links.filter((l) => l.url.trim());
}

function linksEqual(a: SocialLink[], b: SocialLink[]): boolean {
  const norm = (links: SocialLink[]) =>
    normalizeSocialLinks(links)
      .map((l) => `${l.type}:${l.url.trim()}`)
      .sort()
      .join("|");
  return norm(a) === norm(b);
}

// eslint-disable-next-line react-refresh/only-export-components -- draft helpers shared with ProfilePage (#354)
export function isSocialLinksDraftDirty(
  state: SocialLinksDraftState,
  savedLinks: SocialLink[],
): boolean {
  if (!state.isEditing) return false;
  return !linksEqual(state.draft, savedLinks);
}

// eslint-disable-next-line react-refresh/only-export-components -- draft helpers shared with ProfilePage (#354)
export function validateSocialLinksDraft(state: SocialLinksDraftState): {
  ok: boolean;
  filtered: SocialLink[];
  validationErrors: SocialLinksDraftState["validationErrors"];
} {
  const filtered = normalizeSocialLinks(state.draft);
  const validationErrors: SocialLinksDraftState["validationErrors"] = {
    qrz: undefined,
    hamqth: undefined,
    website: undefined,
    twitter: undefined,
    mastodon: undefined,
  };
  for (const link of filtered) {
    const url = link.url.trim();
    if (url && !url.startsWith("http://") && !url.startsWith("https://")) {
      validationErrors[link.type] = "URL must start with http:// or https://";
    }
  }
  const ok = !Object.values(validationErrors).some(Boolean);
  return { ok, filtered, validationErrors };
}

export interface SocialLinksSectionProps {
  state: SocialLinksDraftState;
  onStateChange: (next: SocialLinksDraftState) => void;
}

export function SocialLinksSection({
  state,
  onStateChange,
}: SocialLinksSectionProps) {
  const socialLinks = useProfileStore((s) => s.socialLinks);
  const setSocialLinks = useProfileStore((s) => s.setSocialLinks);

  const { draft, isEditing, validationErrors } = state;

  const patch = (partial: Partial<SocialLinksDraftState>) => {
    onStateChange({ ...state, ...partial });
  };

  const handleEdit = () => {
    onStateChange(createSocialLinksDraftState(socialLinks, true));
  };

  const handleSave = () => {
    const result = validateSocialLinksDraft(state);
    if (!result.ok) {
      patch({ validationErrors: result.validationErrors });
      return;
    }
    setSocialLinks(result.filtered);
    onStateChange(createSocialLinksDraftState(result.filtered, false));
  };

  const handleCancel = () => {
    onStateChange(createSocialLinksDraftState(socialLinks, false));
  };

  const updateLink = (type: SocialLinkType, url: string) => {
    const existing = draft.find((l) => l.type === type);
    const nextDraft = existing
      ? draft.map((l) => (l.type === type ? { ...l, url } : l))
      : [...draft, { type, url }];
    patch({
      draft: nextDraft,
      validationErrors: { ...validationErrors, [type]: undefined },
    });
  };

  const getLinkUrl = (type: SocialLinkType): string => {
    return (
      (isEditing ? draft : socialLinks).find((l) => l.type === type)?.url ?? ""
    );
  };

  const isAutoGenerated = (type: SocialLinkType): boolean => {
    return socialLinks.find((l) => l.type === type)?.autoGenerated ?? false;
  };

  if (!isEditing) {
    const visibleLinks = socialLinks.filter((l) => l.url);
    return (
      <div>
        <div className="flex items-center justify-between mb-2">
          <h3 className="text-sm font-semibold text-su-muted uppercase tracking-wider">
            Links
          </h3>
          <button
            onClick={handleEdit}
            className="text-xs text-plasma-orange hover:text-plasma-orange/80"
          >
            Edit
          </button>
        </div>
        {visibleLinks.length > 0 ? (
          <div className="flex flex-wrap gap-2">
            {visibleLinks.map((link) => {
              const meta = LINK_TYPES.find((t) => t.type === link.type);
              return (
                <a
                  key={link.type}
                  href={link.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  aria-label={`${meta?.label ?? link.type}${link.autoGenerated ? " (auto-generated)" : ""} link`}
                  className="px-2 py-1 rounded text-xs font-medium bg-su-line/10 border border-su-line/40 text-su-muted hover:text-plasma-orange hover:border-plasma-orange/30 transition-colors"
                >
                  {meta?.label ?? link.type}
                  {link.autoGenerated && (
                    <span className="ml-1 text-su-muted">(auto)</span>
                  )}
                </a>
              );
            })}
          </div>
        ) : (
          <p className="text-sm text-su-muted italic">No links added.</p>
        )}
      </div>
    );
  }

  return (
    <div>
      <h3 className="text-sm font-semibold text-su-muted uppercase tracking-wider mb-3">
        Links
      </h3>
      <div className="space-y-3">
        {LINK_TYPES.map((meta) => (
          <div key={meta.type}>
            <label className="block text-xs font-medium text-su-muted mb-1">
              {meta.label}
              {isAutoGenerated(meta.type) && (
                <span className="ml-1 text-su-muted">(auto-generated)</span>
              )}
            </label>
            <input
              type="url"
              value={getLinkUrl(meta.type)}
              onChange={(e) => updateLink(meta.type, e.target.value)}
              placeholder={meta.placeholder}
              className="w-full bg-void-black border border-su-line/40 rounded-lg px-3 py-2 text-sm text-su-text focus:border-plasma-orange/50 focus:outline-none"
            />
            {validationErrors[meta.type] && (
              <p className="mt-1 text-xs text-alert-red">
                {validationErrors[meta.type]}
              </p>
            )}
          </div>
        ))}
      </div>
      <div className="flex gap-2 mt-3">
        <button
          onClick={handleCancel}
          className="px-3 py-1.5 text-xs rounded-lg bg-su-line/10 border border-su-line/40 text-su-muted hover:text-su-text"
        >
          Cancel
        </button>
        <button
          onClick={handleSave}
          className="px-3 py-1.5 text-xs rounded-lg bg-plasma-orange text-su-on-accent hover:bg-plasma-orange/80 font-medium"
        >
          Save Links
        </button>
      </div>
    </div>
  );
}
