/**
 * helpData.ts — Section metadata, search index, and SVG icon components
 * for the Propulse Help Center.
 */

import type { ReactNode } from "react";
import { createElement } from "react";

// ─── SVG Icon Components (24x24, stroke-style, strokeWidth 1.5) ─────────────

function icon(paths: string[], className = "w-6 h-6"): ReactNode {
  return createElement(
    "svg",
    {
      className,
      fill: "none",
      viewBox: "0 0 24 24",
      stroke: "currentColor",
      strokeWidth: 1.5,
    },
    ...paths.map((d, i) =>
      createElement("path", {
        key: i,
        strokeLinecap: "round",
        strokeLinejoin: "round",
        d,
      }),
    ),
  );
}

export const HelpIcons = {
  rocket: (cls?: string) =>
    icon(
      [
        "M15.59 14.37a6 6 0 0 1-5.84 7.38v-4.8m5.84-2.58a14.98 14.98 0 0 0 6.16-12.12A14.98 14.98 0 0 0 9.631 8.41m5.96 5.96a14.926 14.926 0 0 1-5.841 2.58m-.119-8.54a6 6 0 0 0-7.381 5.84h4.8m2.58-5.84a14.927 14.927 0 0 0-2.58 5.84m2.699 2.7c-.103.021-.207.041-.311.06a15.09 15.09 0 0 1-2.448-2.448 14.9 14.9 0 0 1 .06-.312m-2.24 2.39a4.493 4.493 0 0 0-1.757 4.306 4.493 4.493 0 0 0 4.306-1.758M16.5 9a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Z",
      ],
      cls,
    ),
  chartBar: (cls?: string) =>
    icon(
      [
        "M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 0 1 3 19.875v-6.75ZM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V8.625ZM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V4.125Z",
      ],
      cls,
    ),
  sun: (cls?: string) =>
    icon(
      [
        "M12 3v2.25m6.364.386-1.591 1.591M21 12h-2.25m-.386 6.364-1.591-1.591M12 18.75V21m-4.773-4.227-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0Z",
      ],
      cls,
    ),
  globe: (cls?: string) =>
    icon(
      [
        "M12 21a9.004 9.004 0 0 0 8.716-6.747M12 21a9.004 9.004 0 0 1-8.716-6.747M12 21c2.485 0 4.5-4.03 4.5-9S14.485 3 12 3m0 18c-2.485 0-4.5-4.03-4.5-9S9.515 3 12 3m0 0a8.997 8.997 0 0 1 7.843 4.582M12 3a8.997 8.997 0 0 0-7.843 4.582m15.686 0A11.953 11.953 0 0 1 12 10.5c-2.998 0-5.74-1.1-7.843-2.918m15.686 0A8.959 8.959 0 0 1 21 12c0 .778-.099 1.533-.284 2.253m0 0A17.919 17.919 0 0 1 12 16.5a17.92 17.92 0 0 1-8.716-2.247m0 0A8.966 8.966 0 0 1 3 12c0-1.264.26-2.466.732-3.558",
      ],
      cls,
    ),
  crosshair: (cls?: string) =>
    icon(
      [
        "M7.5 3.75H6A2.25 2.25 0 0 0 3.75 6v1.5M16.5 3.75H18A2.25 2.25 0 0 1 20.25 6v1.5m0 9V18A2.25 2.25 0 0 1 18 20.25h-1.5m-9 0H6A2.25 2.25 0 0 1 3.75 18v-1.5M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z",
      ],
      cls,
    ),
  calendar: (cls?: string) =>
    icon(
      [
        "M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 0 1 2.25-2.25h13.5A2.25 2.25 0 0 1 21 7.5v11.25m-18 0A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75m-18 0v-7.5A2.25 2.25 0 0 1 5.25 9h13.5A2.25 2.25 0 0 1 21 11.25v7.5",
      ],
      cls,
    ),
  radio: (cls?: string) =>
    icon(
      [
        "M3.75 7.5h16.5m-16.5 0a1.5 1.5 0 0 0-1.5 1.5v9a1.5 1.5 0 0 0 1.5 1.5h16.5a1.5 1.5 0 0 0 1.5-1.5v-9a1.5 1.5 0 0 0-1.5-1.5m-16.5 0L12 3l8.25 4.5M8.25 15a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Zm6.75 0a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Zm6.75 0a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Z",
      ],
      cls,
    ),
  book: (cls?: string) =>
    icon(
      [
        "M12 6.042A8.967 8.967 0 0 0 6 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 0 1 6 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 0 1 6-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0 0 18 18a8.967 8.967 0 0 0-6 2.292m0-14.25v14.25",
      ],
      cls,
    ),
  trophy: (cls?: string) =>
    icon(
      [
        "M16.5 18.75h-9m9 0a3 3 0 0 1 3 3h-15a3 3 0 0 1 3-3m9 0v-4.5A3.375 3.375 0 0 0 13.125 10.875h-2.25A3.375 3.375 0 0 0 7.5 14.25v4.5m9-13.5V3.375c0-.621-.504-1.125-1.125-1.125h-6.75c-.621 0-1.125.504-1.125 1.125V5.25m9 0H18a2.25 2.25 0 0 1 2.25 2.25v1.5a2.25 2.25 0 0 1-2.25 2.25h-.787M7.5 5.25H6A2.25 2.25 0 0 0 3.75 7.5V9A2.25 2.25 0 0 0 6 11.25h.788",
      ],
      cls,
    ),
  wrench: (cls?: string) =>
    icon(
      [
        "M11.42 15.17 17.25 21A2.652 2.652 0 0 0 21 17.25l-5.877-5.877M11.42 15.17l2.496-3.03c.317-.384.74-.626 1.208-.766M11.42 15.17l-4.655 5.653a2.548 2.548 0 1 1-3.586-3.586l5.653-4.655m5.257-1.412c-.105-.354-.166-.737-.166-1.132a6.008 6.008 0 0 1 6.008-6.008c.543 0 1.068.073 1.567.21L17.16 7.17l.324 1.165 1.165.324 3.086-3.086a6.008 6.008 0 0 1-6.61 7.159Z",
      ],
      cls,
    ),
  gear: (cls?: string) =>
    icon(
      [
        "M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.325.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 0 1 1.37.49l1.296 2.247a1.125 1.125 0 0 1-.26 1.431l-1.003.827c-.293.241-.438.613-.43.992a7.723 7.723 0 0 1 0 .255c-.008.378.137.75.43.991l1.004.827c.424.35.534.955.26 1.43l-1.298 2.248a1.125 1.125 0 0 1-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.47 6.47 0 0 1-.22.128c-.331.183-.581.495-.644.869l-.213 1.281c-.09.543-.56.941-1.11.941h-2.594c-.55 0-1.019-.398-1.11-.94l-.213-1.282c-.062-.373-.312-.686-.644-.87a6.52 6.52 0 0 1-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 0 1-1.369-.49l-1.297-2.247a1.125 1.125 0 0 1 .26-1.431l1.004-.827c.292-.24.437-.613.43-.991a6.932 6.932 0 0 1 0-.255c.007-.38-.138-.751-.43-.992l-1.004-.827a1.125 1.125 0 0 1-.26-1.43l1.297-2.247a1.125 1.125 0 0 1 1.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.087.22-.128.332-.183.582-.495.644-.869l.214-1.28Z",
        "M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z",
      ],
      cls,
    ),
  user: (cls?: string) =>
    icon(
      [
        "M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z",
      ],
      cls,
    ),
  search: (cls?: string) =>
    icon(
      [
        "m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z",
      ],
      cls,
    ),
};

// ─── Section Definitions ─────────────────────────────────────────────────────

export interface HelpSectionDef {
  id: string;
  title: string;
  description: string;
  icon: (cls?: string) => ReactNode;
  keywords: string[];
  featured?: boolean;
}

export const HELP_SECTIONS: HelpSectionDef[] = [
  {
    id: "getting-started",
    title: "Getting Started",
    description: "Overview and quick start guide",
    icon: HelpIcons.rocket,
    keywords: ["start", "begin", "overview", "setup", "quick start", "intro"],
  },
  {
    id: "dashboard",
    title: "Dashboard",
    description: "Home page metrics and band conditions",
    icon: HelpIcons.chartBar,
    keywords: ["home", "bands", "metrics", "kp", "sfi", "band conditions"],
  },
  {
    id: "solar-pulse",
    title: "Solar Pulse",
    description: "Space weather, solar flux, and geomagnetic data",
    icon: HelpIcons.sun,
    keywords: [
      "solar",
      "sun",
      "flux",
      "sfi",
      "aurora",
      "geomagnetic",
      "space weather",
    ],
    featured: true,
  },
  {
    id: "propsphere",
    title: "PropSphere",
    description: "Interactive 3D globe with live spots and propagation paths",
    icon: HelpIcons.globe,
    keywords: ["globe", "map", "3d", "spots", "propagation", "paths", "cesium"],
    featured: true,
  },
  {
    id: "dx-wizard",
    title: "DX Wizard",
    description: "DX cluster spots, filtering, and alerting",
    icon: HelpIcons.crosshair,
    keywords: ["dx", "cluster", "spots", "wizard", "filter", "alerts"],
    featured: true,
  },
  {
    id: "band-planner",
    title: "Band Planner",
    description: "Band-time planning and path projections",
    icon: HelpIcons.calendar,
    keywords: [
      "band",
      "planner",
      "projection",
      "schedule",
      "time",
      "propagation",
    ],
  },
  {
    id: "sdr-console",
    title: "SDR Console",
    description: "Software-defined radio integration and waterfall",
    icon: HelpIcons.radio,
    keywords: ["sdr", "radio", "waterfall", "receiver", "daemon", "audio"],
  },
  {
    id: "logbook",
    title: "Logbook",
    description: "QSO logging, ADIF import/export, and cloud sync",
    icon: HelpIcons.book,
    keywords: ["log", "logbook", "qso", "adif", "import", "export", "contact"],
  },
  {
    id: "contest",
    title: "Contest Logger",
    description: "Contest logging, Cabrillo export, and scoring",
    icon: HelpIcons.trophy,
    keywords: ["contest", "cabrillo", "score", "exchange", "rate"],
  },
  {
    id: "radio-shack",
    title: "Radio Shack",
    description: "Equipment inventory and station setup",
    icon: HelpIcons.wrench,
    keywords: ["shack", "equipment", "radio", "antenna", "rig"],
  },
  {
    id: "settings",
    title: "Settings",
    description: "Preferences, appearance, and configuration",
    icon: HelpIcons.gear,
    keywords: ["settings", "preferences", "theme", "config", "appearance"],
  },
  {
    id: "profile",
    title: "Profile & Account",
    description: "User profile, ranks, badges, and account management",
    icon: HelpIcons.user,
    keywords: ["profile", "account", "rank", "badge", "callsign", "avatar"],
  },
];

// ─── Search Index ────────────────────────────────────────────────────────────

export interface SearchEntry {
  sectionId: string;
  heading: string;
  keywords: string[];
  anchor: string;
}

export const SEARCH_INDEX: SearchEntry[] = [
  // ─── Getting Started ────────────────────────────────────────────────────────
  {
    sectionId: "getting-started",
    heading: "Getting Started",
    keywords: [
      "start",
      "begin",
      "overview",
      "setup",
      "quick start",
      "intro",
      "introduction",
    ],
    anchor: "",
  },
  {
    sectionId: "getting-started",
    heading: "What is Propulse?",
    keywords: [
      "propulse",
      "about",
      "what",
      "introduction",
      "ham radio",
      "propagation",
      "platform",
      "browser",
    ],
    anchor: "what-is-propulse",
  },
  {
    sectionId: "getting-started",
    heading: "Quick Start",
    keywords: [
      "quick",
      "start",
      "begin",
      "first steps",
      "step 1",
      "step 2",
      "step 3",
      "getting started",
    ],
    anchor: "quick-start",
  },
  {
    sectionId: "getting-started",
    heading: "Navigation Overview",
    keywords: ["navigation", "sidebar", "menu", "pages", "nav", "layout"],
    anchor: "navigation-overview",
  },
  {
    sectionId: "getting-started",
    heading: "Account Tiers",
    keywords: [
      "account",
      "free",
      "pro",
      "tier",
      "subscription",
      "plan",
      "pricing",
      "indexeddb",
      "cloud sync",
      "no account",
    ],
    anchor: "account-tiers",
  },
  {
    sectionId: "getting-started",
    heading: "Command Palette",
    keywords: [
      "command palette",
      "ctrl+k",
      "cmd+k",
      "quick navigation",
      "search",
      "jump to",
      "navigate",
    ],
    anchor: "command-palette",
  },
  {
    sectionId: "getting-started",
    heading: "Keyboard Shortcuts",
    keywords: [
      "keyboard",
      "shortcut",
      "hotkey",
      "key",
      "keybind",
      "globe view",
      "flat map",
      "azimuthal",
      "lite mode",
      "band filter",
      "escape",
    ],
    anchor: "keyboard-shortcuts",
  },
  {
    sectionId: "getting-started",
    heading: "Utility Pages",
    keywords: [
      "health",
      "system health",
      "bridge",
      "setup",
      "setup guide",
      "features",
      "feature comparison",
      "sdr setup",
      "daemon setup",
      "utility",
    ],
    anchor: "utility-pages",
  },
  {
    sectionId: "getting-started",
    heading: "Getting Help",
    keywords: [
      "help",
      "bug",
      "feature request",
      "github",
      "community",
      "report",
      "issue",
    ],
    anchor: "getting-help",
  },
  {
    sectionId: "getting-started",
    heading: "FAQ: Do I need an account?",
    keywords: [
      "account",
      "need",
      "required",
      "local",
      "browser",
      "indexeddb",
      "no account",
    ],
    anchor: "faq",
  },
  {
    sectionId: "getting-started",
    heading: "FAQ: Does it work offline?",
    keywords: ["offline", "internet", "connection", "local", "pwa"],
    anchor: "faq",
  },
  {
    sectionId: "getting-started",
    heading: "FAQ: What data do you collect?",
    keywords: [
      "data",
      "privacy",
      "collect",
      "personal",
      "analytics",
      "supabase",
      "tracking",
    ],
    anchor: "faq",
  },
  {
    sectionId: "getting-started",
    heading: "FAQ: What is the Command Palette?",
    keywords: [
      "command palette",
      "ctrl+k",
      "cmd+k",
      "navigation",
      "search",
      "quick jump",
    ],
    anchor: "faq",
  },

  // ─── Dashboard ──────────────────────────────────────────────────────────────
  {
    sectionId: "dashboard",
    heading: "Dashboard Overview",
    keywords: [
      "dashboard",
      "home",
      "overview",
      "command center",
      "hf",
      "propagation",
      "real-time",
    ],
    anchor: "",
  },
  {
    sectionId: "dashboard",
    heading: "Band Conditions",
    keywords: [
      "band",
      "conditions",
      "propagation",
      "hf",
      "160m",
      "80m",
      "40m",
      "20m",
      "15m",
      "10m",
      "good",
      "fair",
      "poor",
      "closed",
      "color",
      "status",
    ],
    anchor: "band-conditions",
  },
  {
    sectionId: "dashboard",
    heading: "Global Conditions Score",
    keywords: [
      "propagation",
      "index",
      "composite",
      "score",
      "gauge",
      "sfi",
      "kp",
      "bz",
      "imf",
      "quality",
    ],
    anchor: "propagation-index",
  },
  {
    sectionId: "dashboard",
    heading: "Primary Metrics",
    keywords: [
      "metrics",
      "kp",
      "k-index",
      "sfi",
      "solar flux",
      "sunspot",
      "ssn",
      "a-index",
      "bz",
      "imf",
      "geomagnetic",
      "magnetometer",
    ],
    anchor: "primary-metrics",
  },
  {
    sectionId: "dashboard",
    heading: "K-Index (Kp)",
    keywords: [
      "kp",
      "k-index",
      "geomagnetic",
      "disturbance",
      "storm",
      "quiet",
      "unsettled",
      "active",
    ],
    anchor: "primary-metrics",
  },
  {
    sectionId: "dashboard",
    heading: "Solar Flux Index (SFI)",
    keywords: [
      "sfi",
      "solar flux",
      "10.7cm",
      "sfu",
      "f-layer",
      "ionization",
      "ionosphere",
    ],
    anchor: "primary-metrics",
  },
  {
    sectionId: "dashboard",
    heading: "Sunspot Number (SSN)",
    keywords: ["sunspot", "ssn", "solar cycle", "cycle 25", "ultraviolet"],
    anchor: "primary-metrics",
  },
  {
    sectionId: "dashboard",
    heading: "Planetary A forecast",
    keywords: ["a-index", "ap", "geomagnetic", "daily", "forecast", "predicted"],
    anchor: "primary-metrics",
  },
  {
    sectionId: "dashboard",
    heading: "Bz (IMF Z-Component)",
    keywords: [
      "bz",
      "imf",
      "interplanetary",
      "magnetic field",
      "nanotesla",
      "southward",
      "northward",
      "magnetosphere",
    ],
    anchor: "primary-metrics",
  },
  {
    sectionId: "dashboard",
    heading: "Activity Cards",
    keywords: [
      "activity",
      "cards",
      "cluster pulse",
      "log stats",
      "predictions",
      "history",
      "dx spots",
    ],
    anchor: "activity-cards",
  },
  {
    sectionId: "dashboard",
    heading: "Cluster Pulse",
    keywords: ["cluster", "pulse", "dx spots", "spot count", "band activity"],
    anchor: "activity-cards",
  },
  {
    sectionId: "dashboard",
    heading: "Log Stats",
    keywords: [
      "log",
      "stats",
      "qso",
      "statistics",
      "contact count",
      "bands worked",
    ],
    anchor: "activity-cards",
  },
  {
    sectionId: "dashboard",
    heading: "Predictions Card",
    keywords: [
      "predictions",
      "forecast",
      "upcoming",
      "events",
      "contest schedule",
      "band openings",
    ],
    anchor: "activity-cards",
  },
  {
    sectionId: "dashboard",
    heading: "History Card",
    keywords: ["history", "trend", "past", "historical", "conditions"],
    anchor: "activity-cards",
  },
  {
    sectionId: "dashboard",
    heading: "Data Sources (Dashboard)",
    keywords: [
      "data",
      "source",
      "noaa",
      "swpc",
      "api",
      "refresh",
      "cache",
      "endpoint",
      "vercel",
      "edge",
    ],
    anchor: "data-sources-dashboard",
  },
  {
    sectionId: "dashboard",
    heading: "FAQ: Why are band conditions changing so fast?",
    keywords: [
      "band",
      "conditions",
      "changing",
      "fast",
      "rapid",
      "k-index",
      "bz",
      "dynamic",
    ],
    anchor: "",
  },
  {
    sectionId: "dashboard",
    heading: "FAQ: What's a good SFI for 10 m?",
    keywords: ["sfi", "10m", "good", "value", "flux", "sporadic-e"],
    anchor: "",
  },
  {
    sectionId: "dashboard",
    heading: "FAQ: How often does data refresh?",
    keywords: ["refresh", "update", "interval", "polling", "rate", "minute"],
    anchor: "",
  },

  // ─── Solar Pulse ────────────────────────────────────────────────────────────
  {
    sectionId: "solar-pulse",
    heading: "Solar Pulse Overview",
    keywords: [
      "solar",
      "pulse",
      "space weather",
      "swpc",
      "noaa",
      "mission control",
    ],
    anchor: "",
  },
  {
    sectionId: "solar-pulse",
    heading: "NOAA Space Weather Scales",
    keywords: [
      "noaa",
      "scales",
      "r-scale",
      "s-scale",
      "g-scale",
      "radio blackout",
      "radiation",
      "geomagnetic storm",
      "severity",
    ],
    anchor: "solar-current-products",
  },
  {
    sectionId: "solar-pulse",
    heading: "R-Scale (Radio Blackouts)",
    keywords: [
      "r-scale",
      "radio",
      "blackout",
      "x-ray",
      "flare",
      "d-layer",
      "absorption",
      "hf degradation",
    ],
    anchor: "solar-impacts",
  },
  {
    sectionId: "solar-pulse",
    heading: "S-Scale (Solar Radiation Storms)",
    keywords: [
      "s-scale",
      "radiation",
      "storm",
      "proton",
      "cme",
      "polar cap",
      "pca",
      "transpolar",
    ],
    anchor: "solar-impacts",
  },
  {
    sectionId: "solar-pulse",
    heading: "G-Scale (Geomagnetic Storms)",
    keywords: [
      "g-scale",
      "geomagnetic",
      "storm",
      "cme",
      "coronal hole",
      "aurora",
      "kp",
    ],
    anchor: "solar-impacts",
  },
  {
    sectionId: "solar-pulse",
    heading: "GOES X-Ray Flare Monitor",
    keywords: [
      "goes",
      "x-ray",
      "flare",
      "monitor",
      "a-class",
      "b-class",
      "c-class",
      "m-class",
      "x-class",
      "satellite",
      "solar flare",
    ],
    anchor: "solar-current-products",
  },
  {
    sectionId: "solar-pulse",
    heading: "Solar Wind",
    keywords: [
      "solar wind",
      "speed",
      "density",
      "bt",
      "bz",
      "l1",
      "lagrange",
      "plasma",
      "cme",
      "coronal hole",
    ],
    anchor: "solar-current-products",
  },
  {
    sectionId: "solar-pulse",
    heading: "Solar Wind Speed",
    keywords: [
      "solar wind",
      "speed",
      "km/s",
      "velocity",
      "coronal hole",
      "high-speed stream",
    ],
    anchor: "solar-current-products",
  },
  {
    sectionId: "solar-pulse",
    heading: "Solar Wind Density",
    keywords: [
      "solar wind",
      "density",
      "proton",
      "particles",
      "cme",
      "shock front",
    ],
    anchor: "solar-current-products",
  },
  {
    sectionId: "solar-pulse",
    heading: "Bt (Total IMF)",
    keywords: [
      "bt",
      "total",
      "imf",
      "interplanetary",
      "magnetic field",
      "nanotesla",
    ],
    anchor: "solar-current-products",
  },
  {
    sectionId: "solar-pulse",
    heading: "Bz (Z-Component)",
    keywords: [
      "bz",
      "imf",
      "z-component",
      "southward",
      "northward",
      "magnetosphere",
      "coupling",
      "storm predictor",
    ],
    anchor: "solar-current-products",
  },
  {
    sectionId: "solar-pulse",
    heading: "Scientific imagery and timelines",
    keywords: [
      "swpc",
      "maps",
      "d-rap",
      "absorption",
      "aurora",
      "imagery",
      "animation",
      "synoptic",
    ],
    anchor: "solar-cycle-imagery",
  },
  {
    sectionId: "solar-pulse",
    heading: "D-RAP Global HF Absorption",
    keywords: [
      "d-rap",
      "absorption",
      "d-layer",
      "hf",
      "blackout",
      "global",
      "map",
    ],
    anchor: "solar-cycle-imagery",
  },
  {
    sectionId: "solar-pulse",
    heading: "D-RAP by Frequency",
    keywords: [
      "d-rap",
      "frequency",
      "20 mhz",
      "10 mhz",
      "absorption",
      "band specific",
    ],
    anchor: "solar-cycle-imagery",
  },
  {
    sectionId: "solar-pulse",
    heading: "Aurora Oval Map",
    keywords: [
      "aurora",
      "oval",
      "ovation",
      "northern hemisphere",
      "polar",
      "vhf scatter",
      "absorption",
    ],
    anchor: "solar-cycle-imagery",
  },
  {
    sectionId: "solar-pulse",
    heading: "Solar Synoptic Map",
    keywords: [
      "synoptic",
      "sun",
      "magnetic",
      "polarity",
      "active region",
      "coronal hole",
      "27-day",
    ],
    anchor: "solar-cycle-imagery",
  },
  {
    sectionId: "solar-pulse",
    heading: "Charts",
    keywords: [
      "chart",
      "graph",
      "time-series",
      "k-index",
      "a-index",
      "solar flux",
      "bz",
      "history",
      "trend",
    ],
    anchor: "solar-current-products",
  },
  {
    sectionId: "solar-pulse",
    heading: "K-Index Chart (24 hours)",
    keywords: ["k-index", "chart", "bar", "24 hours", "geomagnetic", "trend"],
    anchor: "solar-official-forecast",
  },
  {
    sectionId: "solar-pulse",
    heading: "Planetary A forecast",
    keywords: ["a-index", "forecast", "daily", "geomagnetic", "predicted"],
    anchor: "solar-official-forecast",
  },
  {
    sectionId: "solar-pulse",
    heading: "Solar Flux Chart (30 days)",
    keywords: [
      "solar flux",
      "chart",
      "30 days",
      "sfi",
      "trend",
      "solar cycle",
      "27-day recurrence",
    ],
    anchor: "solar-current-products",
  },
  {
    sectionId: "solar-pulse",
    heading: "IMF Bz Chart (1 hour)",
    keywords: ["bz", "chart", "imf", "1 hour", "southward", "real-time"],
    anchor: "solar-current-products",
  },
  {
    sectionId: "solar-pulse",
    heading: "Flare Probabilities",
    keywords: [
      "flare",
      "probability",
      "forecast",
      "c-class",
      "m-class",
      "x-class",
      "proton",
      "next-day",
    ],
    anchor: "solar-official-forecast",
  },
  {
    sectionId: "solar-pulse",
    heading: "Band Conditions Matrix",
    keywords: [
      "band",
      "matrix",
      "conditions",
      "160m",
      "10m",
      "excellent",
      "good",
      "fair",
      "poor",
      "closed",
      "ssb",
      "cw",
      "ft8",
    ],
    anchor: "solar-guidance",
  },
  {
    sectionId: "solar-pulse",
    heading: "Interpreting Conditions",
    keywords: [
      "interpreting",
      "conditions",
      "operating",
      "decisions",
      "best hf",
      "low-band",
      "storm recovery",
      "27-day recurrence",
    ],
    anchor: "solar-guidance",
  },
  {
    sectionId: "solar-pulse",
    heading: "Storm Recovery Propagation",
    keywords: [
      "storm",
      "recovery",
      "enhanced",
      "post-storm",
      "snap back",
      "f-layer",
    ],
    anchor: "solar-guidance",
  },
  {
    sectionId: "solar-pulse",
    heading: "Data Sources (Solar Pulse)",
    keywords: [
      "data",
      "source",
      "endpoint",
      "api",
      "swpc",
      "proxied",
      "direct",
      "refresh",
      "cache",
    ],
    anchor: "solar-current-products",
  },
  {
    sectionId: "solar-pulse",
    heading: "FAQ: What does Bz mean for my QSOs?",
    keywords: [
      "bz",
      "qso",
      "meaning",
      "southward",
      "geomagnetic",
      "early warning",
    ],
    anchor: "",
  },
  {
    sectionId: "solar-pulse",
    heading: "FAQ: How accurate are flare probabilities?",
    keywords: ["flare", "probability", "accuracy", "forecast", "reliable"],
    anchor: "",
  },
  {
    sectionId: "solar-pulse",
    heading: "FAQ: Why does K=5 kill HF?",
    keywords: [
      "kp",
      "k=5",
      "storm",
      "hf",
      "kill",
      "degraded",
      "d-layer",
      "f-layer",
    ],
    anchor: "",
  },

  // ─── PropSphere ─────────────────────────────────────────────────────────────
  {
    sectionId: "propsphere",
    heading: "PropSphere Overview",
    keywords: [
      "propsphere",
      "globe",
      "3d",
      "map",
      "propagation",
      "intelligence",
      "dx spots",
      "visualization",
    ],
    anchor: "",
  },
  {
    sectionId: "propsphere",
    heading: "Map Views",
    keywords: [
      "map",
      "view",
      "globe",
      "flat map",
      "azimuthal",
      "projection",
      "equirectangular",
      "2d",
      "3d",
    ],
    anchor: "map-views",
  },
  {
    sectionId: "propsphere",
    heading: "3D Globe View",
    keywords: [
      "3d",
      "globe",
      "nasa",
      "blue marble",
      "orbit",
      "rotate",
      "zoom",
      "starfield",
      "auto-rotate",
    ],
    anchor: "map-views",
  },
  {
    sectionId: "propsphere",
    heading: "Flat Map (2D) View",
    keywords: [
      "flat map",
      "2d",
      "equirectangular",
      "canvas",
      "pan",
      "zoom",
      "satellite",
      "grayscale",
    ],
    anchor: "map-views",
  },
  {
    sectionId: "propsphere",
    heading: "Azimuthal Equidistant View",
    keywords: [
      "azimuthal",
      "equidistant",
      "great circle",
      "beam heading",
      "antenna pointing",
      "distance rings",
      "bearing",
    ],
    anchor: "map-views",
  },
  {
    sectionId: "propsphere",
    heading: "Layout Modes",
    keywords: [
      "layout",
      "mode",
      "normal",
      "pro",
      "lite",
      "hamclock",
      "fullscreen",
      "floating panels",
      "pills",
    ],
    anchor: "layout-modes",
  },
  {
    sectionId: "propsphere",
    heading: "Normal Layout",
    keywords: [
      "normal",
      "layout",
      "3-panel",
      "band conditions",
      "path analysis",
      "dx cluster",
    ],
    anchor: "layout-modes",
  },
  {
    sectionId: "propsphere",
    heading: "Pro Layout",
    keywords: [
      "pro",
      "layout",
      "fullscreen",
      "floating",
      "draggable",
      "docked",
      "ribbon toolbar",
    ],
    anchor: "layout-modes",
  },
  {
    sectionId: "propsphere",
    heading: "Lite Layout",
    keywords: [
      "lite",
      "layout",
      "minimalist",
      "pills",
      "hud",
      "compact",
      "floating",
    ],
    anchor: "layout-modes",
  },
  {
    sectionId: "propsphere",
    heading: "HamClock Layout",
    keywords: [
      "hamclock",
      "layout",
      "dense",
      "information",
      "dashboard",
      "clock",
    ],
    anchor: "layout-modes",
  },
  {
    sectionId: "propsphere",
    heading: "Observatory Mode",
    keywords: [
      "observatory",
      "lean-back",
      "auto-rotate",
      "passive",
      "monitoring",
      "telescope",
      "fullscreen",
      "display",
    ],
    anchor: "observatory",
  },
  {
    sectionId: "propsphere",
    heading: "Toolbar Reference",
    keywords: [
      "toolbar",
      "buttons",
      "popover",
      "controls",
      "map style",
      "layers",
      "colors",
      "profile",
      "watch",
      "views",
    ],
    anchor: "toolbar",
  },
  {
    sectionId: "propsphere",
    heading: "Map Style Toggle",
    keywords: [
      "map style",
      "satellite",
      "standard",
      "grayscale",
      "night lights",
      "blue marble",
    ],
    anchor: "toolbar",
  },
  {
    sectionId: "propsphere",
    heading: "Layers Popover",
    keywords: [
      "layers",
      "popover",
      "toggle",
      "data layer",
      "terminator",
      "aurora",
      "muf",
      "spots",
    ],
    anchor: "toolbar",
  },
  {
    sectionId: "propsphere",
    heading: "Colors Popover",
    keywords: [
      "colors",
      "popover",
      "spot color",
      "band",
      "mode",
      "signal strength",
      "high-viz",
      "realistic",
    ],
    anchor: "toolbar",
  },
  {
    sectionId: "propsphere",
    heading: "Operating Profiles",
    keywords: [
      "profile",
      "operating",
      "dx hunter",
      "contest",
      "vhf",
      "emergency",
      "listener",
      "custom",
      "preset",
    ],
    anchor: "toolbar",
  },
  {
    sectionId: "propsphere",
    heading: "Watch Popover",
    keywords: [
      "watch",
      "grid",
      "maidenhead",
      "alert",
      "monitor",
      "auto-pan",
      "audio alert",
    ],
    anchor: "toolbar",
  },
  {
    sectionId: "propsphere",
    heading: "Views Popover",
    keywords: [
      "views",
      "region",
      "preset",
      "north america",
      "europe",
      "asia",
      "pacific",
      "custom preset",
      "camera",
    ],
    anchor: "toolbar",
  },
  {
    sectionId: "propsphere",
    heading: "Data Layers Reference",
    keywords: ["layers", "data", "reference", "toggle", "overlay", "16 layers"],
    anchor: "layers",
  },
  {
    sectionId: "propsphere",
    heading: "Day/Night Terminator",
    keywords: [
      "terminator",
      "day",
      "night",
      "boundary",
      "sunset",
      "sunrise",
      "d-layer",
      "subsolar",
    ],
    anchor: "layers",
  },
  {
    sectionId: "propsphere",
    heading: "Greyline",
    keywords: [
      "greyline",
      "grey line",
      "dawn",
      "dusk",
      "terminator",
      "low-band",
      "80m",
      "160m",
      "dx",
    ],
    anchor: "layers",
  },
  {
    sectionId: "propsphere",
    heading: "Aurora Oval Layer",
    keywords: [
      "aurora",
      "oval",
      "ovation",
      "polar",
      "hf absorption",
      "vhf scatter",
      "50 mhz",
      "144 mhz",
    ],
    anchor: "layers",
  },
  {
    sectionId: "propsphere",
    heading: "MUF (Maximum Usable Frequency)",
    keywords: [
      "muf",
      "maximum usable frequency",
      "heatmap",
      "ionosphere",
      "refraction",
      "sfi",
      "color scale",
    ],
    anchor: "layers",
  },
  {
    sectionId: "propsphere",
    heading: "NVIS (Near Vertical Incidence Skywave)",
    keywords: [
      "nvis",
      "near vertical",
      "skywave",
      "emergency",
      "ares",
      "races",
      "80m",
      "40m",
      "0-400 km",
    ],
    anchor: "layers",
  },
  {
    sectionId: "propsphere",
    heading: "Live Spots Layer",
    keywords: [
      "live spots",
      "dx spots",
      "pskreporter",
      "rbn",
      "reverse beacon",
      "dx cluster",
      "deduplication",
      "arc",
    ],
    anchor: "layers",
  },
  {
    sectionId: "propsphere",
    heading: "Spot Traces",
    keywords: [
      "spot traces",
      "animation",
      "missile command",
      "flow",
      "propagation activity",
      "pulse",
    ],
    anchor: "layers",
  },
  {
    sectionId: "propsphere",
    heading: "Night Lights Layer",
    keywords: [
      "night lights",
      "city lights",
      "population",
      "satellite imagery",
      "dark side",
    ],
    anchor: "layers",
  },
  {
    sectionId: "propsphere",
    heading: "Labels Layer",
    keywords: [
      "labels",
      "country borders",
      "state borders",
      "country names",
      "city markers",
      "maidenhead grid",
      "was overlay",
    ],
    anchor: "layers",
  },
  {
    sectionId: "propsphere",
    heading: "Satellites Layer",
    keywords: [
      "satellites",
      "iss",
      "tle",
      "norad",
      "celestrak",
      "orbital",
      "amateur satellite",
      "pass",
    ],
    anchor: "layers",
  },
  {
    sectionId: "propsphere",
    heading: "Earthquakes Layer",
    keywords: [
      "earthquakes",
      "usgs",
      "seismic",
      "magnitude",
      "emergency",
      "disaster",
    ],
    anchor: "layers",
  },
  {
    sectionId: "propsphere",
    heading: "Weather Alerts Layer",
    keywords: [
      "weather",
      "alerts",
      "severe",
      "warnings",
      "watches",
      "advisories",
      "storm",
    ],
    anchor: "layers",
  },
  {
    sectionId: "propsphere",
    heading: "Lightning Layer",
    keywords: [
      "lightning",
      "blitzortung",
      "strikes",
      "thunderstorm",
      "qrn",
      "noise",
      "crowd-sourced",
    ],
    anchor: "layers",
  },
  {
    sectionId: "propsphere",
    heading: "WSPR Layer",
    keywords: [
      "wspr",
      "weak signal",
      "propagation reporter",
      "beacon",
      "wspr.live",
      "low power",
    ],
    anchor: "layers",
  },
  {
    sectionId: "propsphere",
    heading: "Contest QSOs Layer",
    keywords: [
      "contest",
      "qso",
      "layer",
      "coverage",
      "multiplier",
      "geographic",
    ],
    anchor: "layers",
  },
  {
    sectionId: "propsphere",
    heading: "Logged QSOs Layer",
    keywords: [
      "logged",
      "qso",
      "layer",
      "logbook",
      "historical",
      "operating patterns",
    ],
    anchor: "layers",
  },
  {
    sectionId: "propsphere",
    heading: "Fires Layer",
    keywords: [
      "fires",
      "viirs",
      "nasa",
      "firms",
      "wildfire",
      "hotspot",
      "emergency",
    ],
    anchor: "layers",
  },
  {
    sectionId: "propsphere",
    heading: "Weather Radar Layer",
    keywords: ["weather", "radar", "precipitation", "mosaic", "storm"],
    anchor: "layers",
  },
  {
    sectionId: "propsphere",
    heading: "Layer Presets",
    keywords: [
      "layer preset",
      "dx-hunter",
      "contest",
      "vhf",
      "emergency",
      "curated",
      "one click",
    ],
    anchor: "layer-presets",
  },
  {
    sectionId: "propsphere",
    heading: "Display Controls",
    keywords: [
      "display",
      "controls",
      "slider",
      "spot size",
      "pin size",
      "label scale",
      "arc density",
      "auto-rotate",
      "rotation speed",
    ],
    anchor: "display-controls",
  },
  {
    sectionId: "propsphere",
    heading: "Spot Dot Scale",
    keywords: ["spot", "dot", "scale", "size", "0.5x", "2.0x"],
    anchor: "display-controls",
  },
  {
    sectionId: "propsphere",
    heading: "Arc Display Density",
    keywords: [
      "arc",
      "density",
      "propagation arcs",
      "visual",
      "connections",
      "10",
      "200",
    ],
    anchor: "display-controls",
  },
  {
    sectionId: "propsphere",
    heading: "Auto-Rotate Speed",
    keywords: [
      "auto-rotate",
      "speed",
      "rotation",
      "revolution",
      "86400",
      "60 seconds",
    ],
    anchor: "display-controls",
  },
  {
    sectionId: "propsphere",
    heading: "Interactions",
    keywords: [
      "interaction",
      "click",
      "hover",
      "double-click",
      "long-press",
      "right-click",
      "drag",
      "scroll",
      "pinch",
      "touch",
      "mouse",
    ],
    anchor: "interactions",
  },
  {
    sectionId: "propsphere",
    heading: "Click Actions",
    keywords: [
      "click",
      "target",
      "set target",
      "add pin",
      "research grid",
      "toggle watch",
      "flyout",
    ],
    anchor: "interactions",
  },
  {
    sectionId: "propsphere",
    heading: "Hover Tooltips",
    keywords: [
      "hover",
      "tooltip",
      "maidenhead",
      "grid square",
      "spot count",
      "pin flyout",
      "spot detail",
    ],
    anchor: "interactions",
  },
  {
    sectionId: "propsphere",
    heading: "Keyboard Shortcuts (PropSphere)",
    keywords: [
      "keyboard",
      "shortcut",
      "globe",
      "flat map",
      "azimuthal",
      "lite",
      "path",
      "band filter",
      "research",
      "pin",
      "watch",
      "escape",
      "space",
    ],
    anchor: "interactions",
  },
  {
    sectionId: "propsphere",
    heading: "Path Analysis",
    keywords: [
      "path",
      "analysis",
      "great circle",
      "distance",
      "bearing",
      "hops",
      "illumination",
      "difficulty",
      "haversine",
      "slerp",
    ],
    anchor: "path-analysis",
  },
  {
    sectionId: "propsphere",
    heading: "Great Circle Arcs",
    keywords: [
      "great circle",
      "arc",
      "shortest path",
      "short path",
      "long path",
      "slerp",
      "animated",
    ],
    anchor: "path-analysis",
  },
  {
    sectionId: "propsphere",
    heading: "Distance Calculation",
    keywords: [
      "distance",
      "haversine",
      "km",
      "miles",
      "short path",
      "long path",
      "circumference",
    ],
    anchor: "path-analysis",
  },
  {
    sectionId: "propsphere",
    heading: "Bearing & Antenna Pointing",
    keywords: [
      "bearing",
      "azimuth",
      "compass",
      "heading",
      "antenna",
      "pointing",
      "direction",
      "reciprocal",
    ],
    anchor: "path-analysis",
  },
  {
    sectionId: "propsphere",
    heading: "F-Layer Hop Estimation",
    keywords: [
      "hop",
      "f-layer",
      "ionospheric",
      "reflection",
      "3000 km",
      "signal loss",
      "multi-hop",
    ],
    anchor: "path-analysis",
  },
  {
    sectionId: "propsphere",
    heading: "Path Illumination",
    keywords: [
      "illumination",
      "daylight",
      "darkness",
      "subsolar",
      "high bands",
      "low bands",
    ],
    anchor: "path-analysis",
  },
  {
    sectionId: "propsphere",
    heading: "Difficulty Rating",
    keywords: [
      "difficulty",
      "rating",
      "1-5",
      "easy",
      "medium",
      "moderate",
      "hard",
      "extreme",
      "antipodal",
    ],
    anchor: "path-analysis",
  },
  {
    sectionId: "propsphere",
    heading: "Maidenhead Grid System",
    keywords: [
      "maidenhead",
      "grid",
      "locator",
      "field",
      "square",
      "subsquare",
      "extended",
      "fn31",
      "location",
    ],
    anchor: "grid-system",
  },
  {
    sectionId: "propsphere",
    heading: "Grid Hierarchy",
    keywords: [
      "grid",
      "hierarchy",
      "field",
      "square",
      "subsquare",
      "extended",
      "2 letters",
      "4 char",
      "6 char",
    ],
    anchor: "grid-system",
  },
  {
    sectionId: "propsphere",
    heading: "Grid Overlay on Map",
    keywords: [
      "grid",
      "overlay",
      "zoom",
      "field boundaries",
      "square boundaries",
      "subsquare boundaries",
      "labels",
    ],
    anchor: "grid-system",
  },
  {
    sectionId: "propsphere",
    heading: "Data Sources (PropSphere)",
    keywords: [
      "data source",
      "pskreporter",
      "rbn",
      "dx cluster",
      "wspr",
      "blitzortung",
      "nasa firms",
      "usgs",
      "celestrak",
      "norad",
      "noaa",
    ],
    anchor: "data-sources-propsphere",
  },
  {
    sectionId: "propsphere",
    heading: "Spot Deduplication",
    keywords: [
      "deduplication",
      "deduplicate",
      "priority",
      "pskreporter",
      "rbn",
      "wsjt-x",
      "cluster",
    ],
    anchor: "data-sources-propsphere",
  },
  {
    sectionId: "propsphere",
    heading: "Propagation Modeling",
    keywords: [
      "propagation",
      "modeling",
      "muf estimation",
      "band condition",
      "spot correlation",
      "grid glow",
      "ray-trace",
    ],
    anchor: "propagation-modeling",
  },
  {
    sectionId: "propsphere",
    heading: "MUF Estimation Model",
    keywords: [
      "muf",
      "estimation",
      "sfi",
      "time of day",
      "season",
      "latitude",
      "f-layer",
    ],
    anchor: "propagation-modeling",
  },
  {
    sectionId: "propsphere",
    heading: "Band Condition Derivation",
    keywords: [
      "band condition",
      "derivation",
      "sfi",
      "kp",
      "bz",
      "time of day",
      "path geometry",
      "s-units",
      "snr",
    ],
    anchor: "propagation-modeling",
  },
  {
    sectionId: "propsphere",
    heading: "Spot Correlation",
    keywords: [
      "spot correlation",
      "observed",
      "predicted",
      "sporadic-e",
      "validation",
      "model",
    ],
    anchor: "propagation-modeling",
  },
  {
    sectionId: "propsphere",
    heading: "Grid Glow",
    keywords: [
      "grid glow",
      "pulse",
      "5-second",
      "maidenhead",
      "heartbeat",
      "real-time",
    ],
    anchor: "propagation-modeling",
  },
  {
    sectionId: "propsphere",
    heading: "FAQ: How do I center the map on my QTH?",
    keywords: ["center", "map", "qth", "home", "grid square", "settings"],
    anchor: "",
  },
  {
    sectionId: "propsphere",
    heading: "FAQ: What does the MUF layer show?",
    keywords: ["muf", "layer", "heatmap", "frequency", "color", "blue", "red"],
    anchor: "",
  },
  {
    sectionId: "propsphere",
    heading: "FAQ: How are propagation arcs computed?",
    keywords: ["arc", "computed", "great circle", "haversine", "slerp"],
    anchor: "",
  },
  {
    sectionId: "propsphere",
    heading: "FAQ: Why can't I see spots on the map?",
    keywords: [
      "spots",
      "missing",
      "not visible",
      "layer",
      "filter",
      "arc density",
      "internet",
    ],
    anchor: "",
  },
  {
    sectionId: "propsphere",
    heading: "FAQ: How do I save a region view?",
    keywords: [
      "save",
      "view",
      "region",
      "preset",
      "views popover",
      "export",
      "import",
    ],
    anchor: "",
  },
  {
    sectionId: "propsphere",
    heading: "FAQ: Globe vs Flat Map difference?",
    keywords: [
      "globe",
      "flat map",
      "difference",
      "3d",
      "2d",
      "projection",
      "distortion",
    ],
    anchor: "",
  },
  {
    sectionId: "propsphere",
    heading: "FAQ: Layer Presets vs Operating Profiles?",
    keywords: [
      "preset",
      "profile",
      "difference",
      "layers",
      "filter",
      "color",
      "layout",
    ],
    anchor: "",
  },
  {
    sectionId: "propsphere",
    heading: "FAQ: Can I use PropSphere offline?",
    keywords: [
      "offline",
      "propsphere",
      "internet",
      "terminator",
      "greyline",
      "live data",
    ],
    anchor: "",
  },

  // ─── DX Wizard ──────────────────────────────────────────────────────────────
  {
    sectionId: "dx-wizard",
    heading: "DX Wizard Overview",
    keywords: [
      "dx",
      "wizard",
      "transmit",
      "guidance",
      "recommendation",
      "target",
      "band",
      "power",
    ],
    anchor: "",
  },
  {
    sectionId: "dx-wizard",
    heading: "Target Selection",
    keywords: [
      "target",
      "selection",
      "grid",
      "callsign",
      "coordinates",
      "location",
      "lookup",
      "geocode",
      "recent targets",
    ],
    anchor: "target-selection",
  },
  {
    sectionId: "dx-wizard",
    heading: "Callsign Lookup",
    keywords: ["callsign", "lookup", "callook", "api", "resolve", "grid"],
    anchor: "target-selection",
  },
  {
    sectionId: "dx-wizard",
    heading: "Operator Settings",
    keywords: [
      "operator",
      "settings",
      "mode",
      "license",
      "radio",
      "power",
      "ft8",
      "cw",
      "ssb",
      "itu region",
    ],
    anchor: "operator-settings",
  },
  {
    sectionId: "dx-wizard",
    heading: "License Class Selection",
    keywords: [
      "license",
      "class",
      "technician",
      "general",
      "extra",
      "advanced",
      "novice",
      "frequency",
      "authorization",
    ],
    anchor: "operator-settings",
  },
  {
    sectionId: "dx-wizard",
    heading: "ITU Region",
    keywords: [
      "itu",
      "region",
      "itu1",
      "itu2",
      "itu3",
      "band plan",
      "allocation",
    ],
    anchor: "operator-settings",
  },
  {
    sectionId: "dx-wizard",
    heading: "TX Power Ceiling",
    keywords: [
      "tx",
      "power",
      "ceiling",
      "watts",
      "slider",
      "1-1500w",
      "maximum",
      "limit",
    ],
    anchor: "operator-settings",
  },
  {
    sectionId: "dx-wizard",
    heading: "How Recommendations Work",
    keywords: [
      "recommendation",
      "algorithm",
      "snr",
      "baseline",
      "power formula",
      "rank",
      "filter",
      "scoring",
      "band scoring",
    ],
    anchor: "recommendations",
  },
  {
    sectionId: "dx-wizard",
    heading: "SNR Thresholds by Mode",
    keywords: [
      "snr",
      "threshold",
      "ft8",
      "-18 db",
      "cw",
      "-12 db",
      "ssb",
      "-6 db",
      "decode",
    ],
    anchor: "recommendations",
  },
  {
    sectionId: "dx-wizard",
    heading: "Power Estimation Formula",
    keywords: [
      "power",
      "formula",
      "required watts",
      "100w",
      "10 db",
      "estimate",
    ],
    anchor: "recommendations",
  },
  {
    sectionId: "dx-wizard",
    heading: "Mode-Specific Tips",
    keywords: [
      "mode",
      "tips",
      "ft8",
      "cw",
      "ssb",
      "operating",
      "advice",
      "filter",
      "bandwidth",
    ],
    anchor: "mode-tips",
  },
  {
    sectionId: "dx-wizard",
    heading: "FT8 Operating Tips",
    keywords: ["ft8", "filter", "50 hz", "alc", "ntp", "clock", "decode"],
    anchor: "mode-tips",
  },
  {
    sectionId: "dx-wizard",
    heading: "CW Operating Tips",
    keywords: [
      "cw",
      "filter",
      "300 hz",
      "500 hz",
      "sidetone",
      "speed",
      "slow down",
    ],
    anchor: "mode-tips",
  },
  {
    sectionId: "dx-wizard",
    heading: "SSB Operating Tips",
    keywords: [
      "ssb",
      "filter",
      "2.4 khz",
      "compression",
      "processing",
      "speech",
    ],
    anchor: "mode-tips",
  },
  {
    sectionId: "dx-wizard",
    heading: "FAQ: Why recommend a band I can't hear?",
    keywords: [
      "recommend",
      "band",
      "can't hear",
      "noise floor",
      "antenna",
      "local conditions",
    ],
    anchor: "",
  },
  {
    sectionId: "dx-wizard",
    heading: "FAQ: How accurate is the power estimate?",
    keywords: [
      "power",
      "estimate",
      "accuracy",
      "ballpark",
      "6-10 db",
      "real-world",
    ],
    anchor: "",
  },

  // ─── Band Planner ───────────────────────────────────────────────────────────
  {
    sectionId: "band-planner",
    heading: "Band Planner Overview",
    keywords: [
      "band planner",
      "24-hour",
      "projection",
      "estimate",
      "propagation",
      "schedule",
      "operating",
      "windows",
    ],
    anchor: "",
  },
  {
    sectionId: "band-planner",
    heading: "Reading the Heatmap",
    keywords: [
      "heatmap",
      "band",
      "hours",
      "grid",
      "utc",
      "projection",
      "cell",
      "hover",
      "tooltip",
      "snr",
    ],
    anchor: "heatmap",
  },
  {
    sectionId: "band-planner",
    heading: "Status Colors",
    keywords: [
      "status",
      "color",
      "excellent",
      "good",
      "fair",
      "poor",
      "closed",
      "green",
      "orange",
      "red",
      "gray",
      "snr",
    ],
    anchor: "status-colors",
  },
  {
    sectionId: "band-planner",
    heading: "Best Windows",
    keywords: [
      "best",
      "windows",
      "optimal",
      "operating time",
      "contiguous",
      "peak snr",
      "active",
      "upcoming",
      "passed",
    ],
    anchor: "best-windows",
  },
  {
    sectionId: "band-planner",
    heading: "Storms & Evidence",
    keywords: [
      "storm",
      "evidence",
      "kp",
      "bz",
      "geomagnetic",
      "alert",
      "high",
      "medium",
      "low",
      "reliability",
      "disturbed",
    ],
    anchor: "storm-confidence",
  },
  {
    sectionId: "band-planner",
    heading: "Storm Alert Banner",
    keywords: ["storm", "alert", "banner", "kp >= 5", "red", "band closures"],
    anchor: "storm-confidence",
  },
  {
    sectionId: "band-planner",
    heading: "Southward IMF Alert",
    keywords: [
      "southward",
      "imf",
      "bz",
      "alert",
      "yellow",
      "< -5 nt",
      "coupling",
    ],
    anchor: "storm-confidence",
  },
  {
    sectionId: "band-planner",
    heading: "Operating Recommendations",
    keywords: [
      "operating",
      "recommendation",
      "mode",
      "power",
      "guidance",
      "ssb",
      "cw",
      "ft8",
      "digital",
      "qrp",
    ],
    anchor: "operating-recommendations",
  },
  {
    sectionId: "band-planner",
    heading: "Mode Recommendations by Status",
    keywords: [
      "mode",
      "recommendation",
      "excellent",
      "good",
      "fair",
      "poor",
      "ft8",
      "ft4",
      "ssb",
      "digital",
    ],
    anchor: "operating-recommendations",
  },
  {
    sectionId: "band-planner",
    heading: "Power Guidance by SNR",
    keywords: [
      "power",
      "guidance",
      "snr",
      "50w",
      "100w",
      "maximum",
      "qrp",
      "full power",
    ],
    anchor: "operating-recommendations",
  },
  {
    sectionId: "band-planner",
    heading: "Favorites Filter",
    keywords: [
      "favorites",
      "filter",
      "star",
      "preferred bands",
      "subset",
      "hf",
      "antenna",
    ],
    anchor: "favorites-filter",
  },
  {
    sectionId: "band-planner",
    heading: "Data Sources",
    keywords: [
      "data source",
      "solar flux",
      "k-index",
      "bz",
      "noaa",
      "swpc",
      "projection inputs",
    ],
    anchor: "data-sources-planner",
  },
  {
    sectionId: "band-planner",
    heading: "FAQ: Why are all bands closed?",
    keywords: [
      "bands closed",
      "storm",
      "night",
      "kp",
      "lower bands",
      "recovery",
    ],
    anchor: "",
  },
  {
    sectionId: "band-planner",
    heading: "FAQ: What makes Projection Evidence low?",
    keywords: [
      "evidence",
      "low",
      "kp",
      "bz",
      "storm",
      "unpredictable",
      "ionosphere",
    ],
    anchor: "",
  },

  // ─── SDR Console ────────────────────────────────────────────────────────────
  {
    sectionId: "sdr-console",
    heading: "SDR Console Overview",
    keywords: [
      "sdr",
      "console",
      "software defined radio",
      "waterfall",
      "spectrum",
      "daemon",
      "browser",
      "hardware",
    ],
    anchor: "",
  },
  {
    sectionId: "sdr-console",
    heading: "Connecting to a Radio",
    keywords: [
      "connecting",
      "radio",
      "daemon",
      "websocket",
      "device",
      "discovery",
      "auto-reconnect",
      "mdns",
      "ws://127.0.0.1:9867",
    ],
    anchor: "connecting",
  },
  {
    sectionId: "sdr-console",
    heading: "Radio Daemon",
    keywords: [
      "daemon",
      "radio daemon",
      "binary",
      "local",
      "websocket",
      "bridge",
      "propulse",
    ],
    anchor: "connecting",
  },
  {
    sectionId: "sdr-console",
    heading: "Device Discovery",
    keywords: [
      "device",
      "discovery",
      "rtl-sdr",
      "hackrf",
      "hamlib",
      "cat",
      "dropdown",
      "mdns",
    ],
    anchor: "connecting",
  },
  {
    sectionId: "sdr-console",
    heading: "Radio Controls",
    keywords: [
      "radio",
      "controls",
      "frequency",
      "mode",
      "ptt",
      "agc",
      "antenna",
      "gain",
      "tuning",
    ],
    anchor: "radio-controls",
  },
  {
    sectionId: "sdr-console",
    heading: "Frequency Tuning",
    keywords: [
      "frequency",
      "tuning",
      "mhz",
      "khz",
      "hz",
      "bidirectional",
      "sync",
    ],
    anchor: "radio-controls",
  },
  {
    sectionId: "sdr-console",
    heading: "Mode Selection (SDR)",
    keywords: ["mode", "am", "fm", "lsb", "usb", "cw", "sdr"],
    anchor: "radio-controls",
  },
  {
    sectionId: "sdr-console",
    heading: "PTT / Transmit",
    keywords: [
      "ptt",
      "push to talk",
      "transmit",
      "tx",
      "rx only",
      "receive only",
    ],
    anchor: "radio-controls",
  },
  {
    sectionId: "sdr-console",
    heading: "AGC (Automatic Gain Control)",
    keywords: ["agc", "automatic gain control", "gain", "weak signal"],
    anchor: "radio-controls",
  },
  {
    sectionId: "sdr-console",
    heading: "Gain Stages",
    keywords: ["gain", "stages", "lna", "mixer", "if", "slider", "debounce"],
    anchor: "radio-controls",
  },
  {
    sectionId: "sdr-console",
    heading: "DSP Controls",
    keywords: [
      "dsp",
      "digital signal processing",
      "filter",
      "noise reduction",
      "noise blanker",
      "passband",
      "nr",
      "nb",
    ],
    anchor: "dsp-controls",
  },
  {
    sectionId: "sdr-console",
    heading: "Filter (Passband)",
    keywords: [
      "filter",
      "passband",
      "low cutoff",
      "high cutoff",
      "bandwidth",
      "hz",
    ],
    anchor: "dsp-controls",
  },
  {
    sectionId: "sdr-console",
    heading: "Noise Reduction (NR)",
    keywords: ["noise reduction", "nr", "adaptive", "hiss", "hum", "broadband"],
    anchor: "dsp-controls",
  },
  {
    sectionId: "sdr-console",
    heading: "Noise Blanker (NB)",
    keywords: [
      "noise blanker",
      "nb",
      "impulse",
      "ignition",
      "switching",
      "threshold",
    ],
    anchor: "dsp-controls",
  },
  {
    sectionId: "sdr-console",
    heading: "Spectrum & Waterfall",
    keywords: [
      "spectrum",
      "waterfall",
      "fft",
      "display",
      "click-to-tune",
      "zoom",
      "pan",
      "overlay",
      "markers",
    ],
    anchor: "spectrum-waterfall",
  },
  {
    sectionId: "sdr-console",
    heading: "Spectrum Display",
    keywords: [
      "spectrum",
      "fft",
      "4096",
      "20 fps",
      "signal strength",
      "frequency",
    ],
    anchor: "spectrum-waterfall",
  },
  {
    sectionId: "sdr-console",
    heading: "Waterfall Display",
    keywords: [
      "waterfall",
      "time",
      "frequency",
      "history",
      "color",
      "pattern",
      "intermittent",
    ],
    anchor: "spectrum-waterfall",
  },
  {
    sectionId: "sdr-console",
    heading: "Click-to-Tune",
    keywords: ["click", "tune", "spectrum", "waterfall", "jump", "frequency"],
    anchor: "spectrum-waterfall",
  },
  {
    sectionId: "sdr-console",
    heading: "WSJT-X Integration",
    keywords: [
      "wsjt-x",
      "wsjtx",
      "udp",
      "ft8",
      "ft4",
      "jt65",
      "decode",
      "digital mode",
      "integration",
      "2237",
    ],
    anchor: "wsjtx",
  },
  {
    sectionId: "sdr-console",
    heading: "WSJT-X Decode Table",
    keywords: [
      "decode",
      "table",
      "timestamp",
      "snr",
      "delta",
      "message",
      "200",
      "fifo",
    ],
    anchor: "wsjtx",
  },
  {
    sectionId: "sdr-console",
    heading: "DX Cluster Overlay",
    keywords: [
      "dx cluster",
      "overlay",
      "waterfall",
      "spot markers",
      "orange",
      "callsign",
      "click to tune",
    ],
    anchor: "cluster-overlay",
  },
  {
    sectionId: "sdr-console",
    heading: "Bridge & Daemon Setup",
    keywords: [
      "bridge",
      "daemon",
      "setup",
      "install",
      "binary",
      "windows",
      "macos",
      "linux",
      "raspberry pi",
      "configuration",
      "https",
      "mixed content",
    ],
    anchor: "daemon-setup",
  },
  {
    sectionId: "sdr-console",
    heading: "Daemon Installation",
    keywords: [
      "install",
      "daemon",
      "download",
      "windows",
      "macos",
      "linux",
      "chmod",
      "firewall",
      "port 9867",
    ],
    anchor: "daemon-setup",
  },
  {
    sectionId: "sdr-console",
    heading: "HTTPS / Mixed Content",
    keywords: [
      "https",
      "mixed content",
      "chrome extension",
      "bridge extension",
      "localhost",
      "wss",
      "ws",
    ],
    anchor: "daemon-setup",
  },
  {
    sectionId: "sdr-console",
    heading: "Supported Hardware",
    keywords: [
      "hardware",
      "rtl-sdr",
      "hackrf",
      "cat",
      "hamlib",
      "sdrconnect",
      "yaesu",
      "kenwood",
      "icom",
      "elecraft",
      "flexradio",
    ],
    anchor: "hardware",
  },
  {
    sectionId: "sdr-console",
    heading: "Data Sources",
    keywords: [
      "data source",
      "websocket",
      "udp",
      "wsjt-x",
      "daemon",
      "fft",
      "audio stream",
      "port 9867",
      "port 2237",
    ],
    anchor: "data-sources-sdr",
  },
  {
    sectionId: "sdr-console",
    heading: "FAQ: How do I install the daemon?",
    keywords: [
      "install",
      "daemon",
      "download",
      "binary",
      "github",
      "port 9867",
    ],
    anchor: "",
  },
  {
    sectionId: "sdr-console",
    heading: "FAQ: Which SDR devices are supported?",
    keywords: [
      "sdr",
      "device",
      "supported",
      "rtl-sdr",
      "hackrf",
      "cat",
      "hamlib",
    ],
    anchor: "",
  },
  {
    sectionId: "sdr-console",
    heading: "FAQ: Why can't I transmit?",
    keywords: ["transmit", "tx", "ptt", "rx only", "rtl-sdr", "hackrf", "cat"],
    anchor: "",
  },

  // ─── Logbook ────────────────────────────────────────────────────────────────
  {
    sectionId: "logbook",
    heading: "Logbook Overview",
    keywords: [
      "logbook",
      "qso",
      "log",
      "contact",
      "digital",
      "station log",
      "adif",
      "cloud sync",
    ],
    anchor: "",
  },
  {
    sectionId: "logbook",
    heading: "Logging a QSO",
    keywords: [
      "logging",
      "qso",
      "new qso",
      "callsign",
      "band",
      "mode",
      "date",
      "time",
      "rst",
      "frequency",
      "grid",
      "auto-populate",
    ],
    anchor: "logging-qso",
  },
  {
    sectionId: "logbook",
    heading: "QSO Required Fields",
    keywords: [
      "required",
      "fields",
      "callsign",
      "band",
      "mode",
      "date",
      "time",
      "utc",
    ],
    anchor: "logging-qso",
  },
  {
    sectionId: "logbook",
    heading: "QSO Optional Fields",
    keywords: [
      "optional",
      "fields",
      "rst",
      "frequency",
      "grid",
      "notes",
      "power",
      "operator name",
    ],
    anchor: "logging-qso",
  },
  {
    sectionId: "logbook",
    heading: "Callsign Auto-Population",
    keywords: [
      "auto-populate",
      "callsign",
      "lookup",
      "grid",
      "name",
      "qth",
      "auto-complete",
    ],
    anchor: "logging-qso",
  },
  {
    sectionId: "logbook",
    heading: "ADIF Import/Export",
    keywords: [
      "adif",
      "import",
      "export",
      "file",
      ".adi",
      ".adif",
      "standard",
      "3.x",
      "lotw",
      "eqsl",
      "clublog",
      "n1mm",
      "log4om",
    ],
    anchor: "adif",
  },
  {
    sectionId: "logbook",
    heading: "ADIF Import",
    keywords: [
      "adif",
      "import",
      "upload",
      "file",
      "paste",
      "duplicate detection",
    ],
    anchor: "adif",
  },
  {
    sectionId: "logbook",
    heading: "ADIF Export",
    keywords: ["adif", "export", "download", "propulse-log", "backup"],
    anchor: "adif",
  },
  {
    sectionId: "logbook",
    heading: "Guest Mode",
    keywords: [
      "guest",
      "mode",
      "session",
      "visiting",
      "operator",
      "field day",
      "club station",
      "shared",
      "separate storage",
    ],
    anchor: "guest-mode",
  },
  {
    sectionId: "logbook",
    heading: "Awards Tracker",
    keywords: [
      "awards",
      "tracker",
      "was",
      "worked all states",
      "dxcc",
      "progress",
      "confirmed",
      "entities",
      "states",
    ],
    anchor: "awards",
  },
  {
    sectionId: "logbook",
    heading: "WAS (Worked All States)",
    keywords: [
      "was",
      "worked all states",
      "50 states",
      "us states",
      "confirmed",
    ],
    anchor: "awards",
  },
  {
    sectionId: "logbook",
    heading: "DXCC Tracking",
    keywords: [
      "dxcc",
      "countries",
      "entities",
      "territories",
      "prefix",
      "confirmed",
    ],
    anchor: "awards",
  },
  {
    sectionId: "logbook",
    heading: "External Services",
    keywords: [
      "external",
      "services",
      "lotw",
      "eqsl",
      "clublog",
      "upload",
      "sync",
      "qsl",
      "confirmation",
    ],
    anchor: "external-services",
  },
  {
    sectionId: "logbook",
    heading: "LoTW (Logbook of The World)",
    keywords: [
      "lotw",
      "logbook of the world",
      "arrl",
      "tq6",
      "certificate",
      "qsl",
    ],
    anchor: "external-services",
  },
  {
    sectionId: "logbook",
    heading: "eQSL",
    keywords: ["eqsl", "electronic qsl", "card", "virtual", "exchange"],
    anchor: "external-services",
  },
  {
    sectionId: "logbook",
    heading: "ClubLog",
    keywords: ["clublog", "dxcc", "expedition", "api key", "analysis"],
    anchor: "external-services",
  },
  {
    sectionId: "logbook",
    heading: "Local vs Cloud Storage",
    keywords: [
      "local",
      "cloud",
      "storage",
      "localstorage",
      "indexeddb",
      "supabase",
      "sync",
      "backup",
      "no account",
      "free account",
      "pro",
    ],
    anchor: "storage",
  },
  {
    sectionId: "logbook",
    heading: "FAQ: Can I import my old logbook?",
    keywords: [
      "import",
      "old",
      "logbook",
      "adif",
      "n1mm",
      "log4om",
      "hrd",
      "duplicate",
    ],
    anchor: "",
  },
  {
    sectionId: "logbook",
    heading: "FAQ: What format does export use?",
    keywords: ["export", "format", "adif", "3.x", ".adi", "compatible"],
    anchor: "",
  },
  {
    sectionId: "logbook",
    heading: "FAQ: Does guest mode affect my log?",
    keywords: ["guest", "mode", "affect", "log", "separate", "session"],
    anchor: "",
  },

  // ─── Contest ────────────────────────────────────────────────────────────────
  {
    sectionId: "contest",
    heading: "Contest Logger Overview",
    keywords: [
      "contest",
      "logger",
      "scoring",
      "multiplier",
      "rate",
      "off-time",
      "cabrillo",
      "keyboard",
      "wsjt-x",
    ],
    anchor: "",
  },
  {
    sectionId: "contest",
    heading: "Getting Started (Contest)",
    keywords: [
      "contest",
      "start",
      "configuration",
      "select",
      "exchange",
      "category",
      "cq ww",
      "sweepstakes",
      "field day",
      "cabrillo",
    ],
    anchor: "contest-start",
  },
  {
    sectionId: "contest",
    heading: "Contest Exchange Setup",
    keywords: [
      "exchange",
      "setup",
      "59",
      "1a",
      "zone",
      "section",
      "cabrillo",
      "metadata",
    ],
    anchor: "contest-start",
  },
  {
    sectionId: "contest",
    heading: "One-Line Entry",
    keywords: [
      "one-line",
      "entry",
      "keyboard",
      "fast",
      "logging",
      "callsign",
      "rst",
      "exchange",
      "tab",
      "enter",
      "dupe",
      "multiplier",
    ],
    anchor: "one-line-entry",
  },
  {
    sectionId: "contest",
    heading: "Dupe Check",
    keywords: [
      "dupe",
      "duplicate",
      "check",
      "warning",
      "band",
      "mode",
      "real-time",
    ],
    anchor: "one-line-entry",
  },
  {
    sectionId: "contest",
    heading: "New Multiplier Indicator",
    keywords: ["new mult", "multiplier", "badge", "indicator", "valuable"],
    anchor: "one-line-entry",
  },
  {
    sectionId: "contest",
    heading: "Contest Keyboard Hotkeys",
    keywords: [
      "hotkey",
      "keyboard",
      "shortcut",
      "enter",
      "escape",
      "ctrl+z",
      "ctrl+e",
      "alt",
      "band select",
      "f1",
      "macro",
    ],
    anchor: "contest-hotkeys",
  },
  {
    sectionId: "contest",
    heading: "Band Quick Select",
    keywords: [
      "band",
      "select",
      "alt+1",
      "alt+2",
      "alt+3",
      "alt+4",
      "alt+5",
      "alt+6",
      "160m",
      "80m",
      "40m",
      "20m",
      "15m",
      "10m",
    ],
    anchor: "contest-hotkeys",
  },
  {
    sectionId: "contest",
    heading: "Live Scoring",
    keywords: [
      "scoring",
      "live",
      "qso count",
      "total points",
      "multiplier",
      "rolling rate",
      "projection",
      "last qso delta",
    ],
    anchor: "scoring",
  },
  {
    sectionId: "contest",
    heading: "Rolling Rates",
    keywords: [
      "rate",
      "rolling",
      "10-minute",
      "60-minute",
      "qso/hour",
      "trend",
    ],
    anchor: "scoring",
  },
  {
    sectionId: "contest",
    heading: "Score Projection",
    keywords: [
      "projection",
      "estimated",
      "final score",
      "elapsed time",
      "current rate",
    ],
    anchor: "scoring",
  },
  {
    sectionId: "contest",
    heading: "Rate Sheet",
    keywords: [
      "rate sheet",
      "hourly",
      "10-minute",
      "band-by-hour",
      "heatmap",
      "peak",
      "analysis",
    ],
    anchor: "rate-sheet",
  },
  {
    sectionId: "contest",
    heading: "Off-Time Rules",
    keywords: [
      "off-time",
      "operating time",
      "48-hour",
      "30-hour",
      "36 hours",
      "24 hours",
      "minimum",
      "60 minutes",
      "timer",
    ],
    anchor: "off-time",
  },
  {
    sectionId: "contest",
    heading: "CAT Integration (Contest)",
    keywords: [
      "cat",
      "rig",
      "integration",
      "band sync",
      "mode sync",
      "automatic",
      "lsb",
      "usb",
      "cw",
      "ft8",
      "mapping",
    ],
    anchor: "cat-integration",
  },
  {
    sectionId: "contest",
    heading: "Multiplier Panel",
    keywords: [
      "multiplier",
      "panel",
      "worked",
      "needed",
      "not available",
      "per-band",
      "priority",
    ],
    anchor: "multipliers",
  },
  {
    sectionId: "contest",
    heading: "Score Sharing",
    keywords: [
      "score",
      "sharing",
      "export",
      "clipboard",
      "social media",
      "summary",
      "contest history",
    ],
    anchor: "score-sharing",
  },
  {
    sectionId: "contest",
    heading: "Cabrillo Export",
    keywords: ["cabrillo", "export", "submit", "contest", "log", "file"],
    anchor: "contest-start",
  },
  {
    sectionId: "contest",
    heading: "FAQ: How are points calculated?",
    keywords: [
      "points",
      "calculated",
      "formula",
      "contest rules",
      "multiplier",
      "cq ww",
      "continent",
    ],
    anchor: "",
  },
  {
    sectionId: "contest",
    heading: "FAQ: What happens when I run out of operating time?",
    keywords: [
      "operating time",
      "run out",
      "limit",
      "penalty",
      "off-time",
      "strategic",
    ],
    anchor: "",
  },
  {
    sectionId: "contest",
    heading: "FAQ: Can I edit a logged QSO?",
    keywords: ["edit", "qso", "ctrl+e", "click", "row", "recalculate"],
    anchor: "",
  },

  // ─── Radio Shack ────────────────────────────────────────────────────────────
  {
    sectionId: "radio-shack",
    heading: "Radio Shack Overview",
    keywords: [
      "radio shack",
      "shack",
      "equipment",
      "inventory",
      "station",
      "diagram",
      "performance",
      "virtual",
    ],
    anchor: "",
  },
  {
    sectionId: "radio-shack",
    heading: "Equipment Management",
    keywords: [
      "equipment",
      "management",
      "radios",
      "antennas",
      "feedlines",
      "inline",
      "accessories",
      "setup wizard",
      "categories",
    ],
    anchor: "equipment",
  },
  {
    sectionId: "radio-shack",
    heading: "Radios (Equipment)",
    keywords: [
      "radios",
      "transceiver",
      "receiver",
      "manufacturer",
      "model",
      "power output",
      "modes",
      "frequency range",
    ],
    anchor: "equipment",
  },
  {
    sectionId: "radio-shack",
    heading: "Antennas (Equipment)",
    keywords: [
      "antennas",
      "dipole",
      "yagi",
      "vertical",
      "loop",
      "gain",
      "radiation pattern",
      "bands supported",
    ],
    anchor: "equipment",
  },
  {
    sectionId: "radio-shack",
    heading: "Feedlines (Equipment)",
    keywords: [
      "feedlines",
      "coaxial",
      "cable",
      "rg-8",
      "rg-213",
      "lmr-400",
      "length",
      "loss",
      "transmission line",
    ],
    anchor: "equipment",
  },
  {
    sectionId: "radio-shack",
    heading: "Inline Components",
    keywords: [
      "inline",
      "components",
      "tuner",
      "amplifier",
      "switch",
      "insertion loss",
      "gain",
    ],
    anchor: "equipment",
  },
  {
    sectionId: "radio-shack",
    heading: "Signal Path Diagram",
    keywords: [
      "signal path",
      "diagram",
      "station builder lab",
      "canvas",
      "chain",
      "zoom",
      "pan",
      "drag",
      "connection",
      "impedance",
      "mismatch",
    ],
    anchor: "signal-path",
  },
  {
    sectionId: "radio-shack",
    heading: "Station Builder Lab",
    keywords: [
      "station builder",
      "lab",
      "visual",
      "canvas",
      "signal chain",
      "nodes",
      "loss budget bar",
    ],
    anchor: "signal-path",
  },
  {
    sectionId: "radio-shack",
    heading: "Impedance Mismatch Warning",
    keywords: ["impedance", "mismatch", "warning", "swr", "tuner", "connector"],
    anchor: "signal-path",
  },
  {
    sectionId: "radio-shack",
    heading: "Performance Analysis",
    keywords: [
      "performance",
      "analysis",
      "loss budget",
      "erp",
      "snr",
      "band capability",
      "effective radiated power",
    ],
    anchor: "performance",
  },
  {
    sectionId: "radio-shack",
    heading: "Loss Budget",
    keywords: [
      "loss budget",
      "feedline loss",
      "connector loss",
      "tuner loss",
      "switch loss",
      "db",
      "per foot",
    ],
    anchor: "performance",
  },
  {
    sectionId: "radio-shack",
    heading: "Effective Radiated Power (ERP)",
    keywords: [
      "erp",
      "effective radiated power",
      "dbm",
      "dbi",
      "antenna gain",
      "path loss",
      "formula",
    ],
    anchor: "performance",
  },
  {
    sectionId: "radio-shack",
    heading: "SNR at Receiver",
    keywords: [
      "snr",
      "receiver",
      "receive sensitivity",
      "antenna gain",
      "noise figure",
    ],
    anchor: "performance",
  },
  {
    sectionId: "radio-shack",
    heading: "Band Capability Matrix",
    keywords: [
      "band capability",
      "matrix",
      "effective power",
      "coverage",
      "gaps",
      "supported bands",
    ],
    anchor: "performance",
  },
  {
    sectionId: "radio-shack",
    heading: "What-If Simulator",
    keywords: [
      "what-if",
      "simulator",
      "compare",
      "experiment",
      "swap",
      "parameter",
      "preset",
      "purchasing",
    ],
    anchor: "what-if",
  },
  {
    sectionId: "radio-shack",
    heading: "Equipment Database",
    keywords: [
      "equipment database",
      "pre-loaded",
      "manufacturer",
      "specifications",
      "auto-fill",
      "custom",
    ],
    anchor: "equipment-database",
  },
  {
    sectionId: "radio-shack",
    heading: "FAQ: How is feedline loss calculated?",
    keywords: [
      "feedline",
      "loss",
      "calculated",
      "per 100 feet",
      "frequency",
      "swr",
      "mismatch",
    ],
    anchor: "",
  },
  {
    sectionId: "radio-shack",
    heading: "FAQ: What's ERP?",
    keywords: [
      "erp",
      "effective radiated power",
      "antenna",
      "feedline",
      "gain",
      "loss",
    ],
    anchor: "",
  },
  {
    sectionId: "radio-shack",
    heading: "FAQ: Can I add custom equipment?",
    keywords: [
      "custom",
      "equipment",
      "add",
      "manual",
      "specifications",
      "database",
    ],
    anchor: "",
  },

  // ─── Settings ───────────────────────────────────────────────────────────────
  {
    sectionId: "settings",
    heading: "Settings Overview",
    keywords: [
      "settings",
      "preferences",
      "config",
      "configuration",
      "gear",
      "sidebar",
      "instant",
      "no save button",
    ],
    anchor: "",
  },
  {
    sectionId: "settings",
    heading: "Preferences",
    keywords: [
      "preferences",
      "display",
      "accessibility",
      "map",
      "globe",
      "propagation",
      "forecast",
      "interaction",
      "bands",
    ],
    anchor: "preferences",
  },
  {
    sectionId: "settings",
    heading: "Time Format",
    keywords: ["time", "format", "24-hour", "12-hour", "clock", "timestamp"],
    anchor: "preferences",
  },
  {
    sectionId: "settings",
    heading: "Text Size",
    keywords: [
      "text",
      "size",
      "small",
      "normal",
      "large",
      "readability",
      "font",
    ],
    anchor: "preferences",
  },
  {
    sectionId: "settings",
    heading: "Visual Style",
    keywords: [
      "visual",
      "style",
      "realistic",
      "high-viz",
      "high contrast",
      "rendering",
    ],
    anchor: "preferences",
  },
  {
    sectionId: "settings",
    heading: "Color Vision / Accessibility",
    keywords: [
      "color vision",
      "accessibility",
      "colorblind",
      "protanopia",
      "deuteranopia",
      "tritanopia",
      "achromatopsia",
      "high contrast",
      "reduced motion",
    ],
    anchor: "preferences",
  },
  {
    sectionId: "settings",
    heading: "Spot Clustering",
    keywords: [
      "spot",
      "clustering",
      "group",
      "grid size",
      "minimum cluster",
      "visual clutter",
    ],
    anchor: "preferences",
  },
  {
    sectionId: "settings",
    heading: "Compass Rose",
    keywords: [
      "compass",
      "rose",
      "beam width",
      "wedge",
      "antenna coverage",
      "qth",
    ],
    anchor: "preferences",
  },
  {
    sectionId: "settings",
    heading: "Spot Age Display",
    keywords: [
      "spot",
      "age",
      "fade",
      "maximum age",
      "5 minutes",
      "120 minutes",
    ],
    anchor: "preferences",
  },
  {
    sectionId: "settings",
    heading: "Callsign & Spotter Labels",
    keywords: [
      "callsign",
      "labels",
      "spotter",
      "globe",
      "markers",
      "identification",
    ],
    anchor: "preferences",
  },
  {
    sectionId: "settings",
    heading: "Spot Color Mode",
    keywords: [
      "spot color",
      "mode",
      "band",
      "operating mode",
      "cw",
      "ssb",
      "ft8",
    ],
    anchor: "preferences",
  },
  {
    sectionId: "settings",
    heading: "Noise Environment",
    keywords: [
      "noise",
      "environment",
      "quiet rural",
      "rural",
      "suburban",
      "urban",
      "city",
      "itu-r p.372",
      "man-made noise",
    ],
    anchor: "preferences",
  },
  {
    sectionId: "settings",
    heading: "Antenna Type (Settings)",
    keywords: [
      "antenna",
      "type",
      "isotropic",
      "dipole",
      "vertical",
      "yagi",
      "gain",
      "dbi",
      "elevation angle",
    ],
    anchor: "preferences",
  },
  {
    sectionId: "settings",
    heading: "Forecast Display Settings",
    keywords: [
      "forecast",
      "display",
      "band mode",
      "common",
      "all",
      "custom",
      "snr values",
      "hours",
      "13",
      "24",
    ],
    anchor: "preferences",
  },
  {
    sectionId: "settings",
    heading: "Interaction Settings",
    keywords: [
      "interaction",
      "hover tips",
      "hold duration",
      "context menu",
      "auto-dismiss",
      "flyout",
    ],
    anchor: "preferences",
  },
  {
    sectionId: "settings",
    heading: "Favored Bands",
    keywords: [
      "favored",
      "bands",
      "favorite",
      "selection",
      "presets",
      "contest hf",
      "ft8 bands",
      "low band dx",
    ],
    anchor: "preferences",
  },
  {
    sectionId: "settings",
    heading: "Appearance",
    keywords: [
      "appearance",
      "theme",
      "accent color",
      "custom colors",
      "sdr waterfall palette",
      "preview",
    ],
    anchor: "appearance",
  },
  {
    sectionId: "settings",
    heading: "Accent Color",
    keywords: [
      "accent",
      "color",
      "plasma",
      "orange",
      "green",
      "preset",
      "highlight",
    ],
    anchor: "appearance",
  },
  {
    sectionId: "settings",
    heading: "Custom Colors",
    keywords: ["custom", "colors", "hex", "rgb", "rrggbb", "apply", "reset"],
    anchor: "appearance",
  },
  {
    sectionId: "settings",
    heading: "Theme Selection",
    keywords: [
      "theme",
      "dark",
      "background",
      "panel style",
      "hamshack",
      "low light",
    ],
    anchor: "appearance",
  },
  {
    sectionId: "settings",
    heading: "SDR Waterfall Palette",
    keywords: [
      "sdr",
      "waterfall",
      "palette",
      "classic",
      "viridis",
      "magma",
      "grayscale",
      "spectrum",
    ],
    anchor: "appearance",
  },
  {
    sectionId: "settings",
    heading: "Notifications",
    keywords: [
      "notifications",
      "alerts",
      "greyline",
      "storm",
      "flare",
      "band opening",
      "sound",
      "watch",
      "quiet hours",
    ],
    anchor: "notifications",
  },
  {
    sectionId: "settings",
    heading: "Greyline Alerts",
    keywords: [
      "greyline",
      "alert",
      "sunrise",
      "sunset",
      "terminator",
      "low-band dx",
    ],
    anchor: "notifications",
  },
  {
    sectionId: "settings",
    heading: "Geomagnetic Storm Warnings",
    keywords: [
      "geomagnetic",
      "storm",
      "warning",
      "kp",
      "threshold",
      "notification",
    ],
    anchor: "notifications",
  },
  {
    sectionId: "settings",
    heading: "Solar Flare Alerts",
    keywords: ["solar", "flare", "alert", "notification", "hf impact"],
    anchor: "notifications",
  },
  {
    sectionId: "settings",
    heading: "Band Opening Notifications",
    keywords: [
      "band opening",
      "notification",
      "inter-continental",
      "activity",
      "band selector",
    ],
    anchor: "notifications",
  },
  {
    sectionId: "settings",
    heading: "Sound Controls",
    keywords: ["sound", "audio", "mute", "enabled", "disabled", "visual only"],
    anchor: "notifications",
  },
  {
    sectionId: "settings",
    heading: "Watch Alerts",
    keywords: [
      "watch",
      "alert",
      "grid square",
      "callsign",
      "region",
      "sunrise",
      "sunset",
      "geomagnetic",
    ],
    anchor: "notifications",
  },
  {
    sectionId: "settings",
    heading: "Quiet Hours",
    keywords: [
      "quiet hours",
      "suppress",
      "utc",
      "start",
      "end",
      "silent",
      "no sound",
    ],
    anchor: "notifications",
  },
  {
    sectionId: "settings",
    heading: "Connections",
    keywords: [
      "connections",
      "bridge",
      "dx cluster",
      "cat",
      "rig control",
      "hamlib",
      "flrig",
      "websocket",
    ],
    anchor: "connections",
  },
  {
    sectionId: "settings",
    heading: "ProPulse Bridge",
    keywords: [
      "propulse bridge",
      "companion",
      "local",
      "websocket",
      "dx cluster",
      "cat",
      "wsjt-x",
    ],
    anchor: "connections",
  },
  {
    sectionId: "settings",
    heading: "DX Cluster Connection",
    keywords: [
      "dx cluster",
      "node",
      "ve7cc",
      "nc7j",
      "hb9drv",
      "k3lr",
      "spot filter",
      "login callsign",
      "password",
    ],
    anchor: "connections",
  },
  {
    sectionId: "settings",
    heading: "CAT / Rig Control",
    keywords: [
      "cat",
      "rig",
      "control",
      "hamlib",
      "rigctld",
      "flrig",
      "frequency",
      "mode",
      "s-meter",
      "ptt",
      "safety lockout",
    ],
    anchor: "connections",
  },
  {
    sectionId: "settings",
    heading: "Subscription",
    keywords: [
      "subscription",
      "plan",
      "free",
      "pro",
      "upgrade",
      "billing",
      "stripe",
      "price",
      "$6.99",
      "manage",
    ],
    anchor: "subscription",
  },
  {
    sectionId: "settings",
    heading: "Plan Comparison",
    keywords: [
      "plan",
      "comparison",
      "cloud sync",
      "custom images",
      "propagation modeling",
      "spot replay",
      "history",
      "arc density",
    ],
    anchor: "subscription",
  },
  {
    sectionId: "settings",
    heading: "Data & Account",
    keywords: [
      "data",
      "account",
      "export",
      "import",
      "settings",
      "logbook",
      "clear",
      "local data",
      "backup",
      "json",
      "about",
      "version",
    ],
    anchor: "data-account",
  },
  {
    sectionId: "settings",
    heading: "Export / Import Settings",
    keywords: [
      "export",
      "import",
      "settings",
      "json",
      "backup",
      "restore",
      "preferences",
      "targets",
      "watches",
      "pins",
    ],
    anchor: "data-account",
  },
  {
    sectionId: "settings",
    heading: "Export Logbook (Settings)",
    keywords: ["export", "logbook", "adif", "download", "qso count"],
    anchor: "data-account",
  },
  {
    sectionId: "settings",
    heading: "Clear Local Data",
    keywords: [
      "clear",
      "local data",
      "delete",
      "reset",
      "localstorage",
      "indexeddb",
      "double-click",
      "irreversible",
    ],
    anchor: "data-account",
  },
  {
    sectionId: "settings",
    heading: "FAQ: How do I change my callsign?",
    keywords: ["change", "callsign", "profile", "station identity", "sidebar"],
    anchor: "",
  },
  {
    sectionId: "settings",
    heading: "FAQ: Can I reset all settings to defaults?",
    keywords: ["reset", "defaults", "clear", "data", "account", "local"],
    anchor: "",
  },
  {
    sectionId: "settings",
    heading: "FAQ: Where is my data stored?",
    keywords: [
      "data",
      "stored",
      "localstorage",
      "indexeddb",
      "supabase",
      "cloud",
      "encrypted",
      "tls",
    ],
    anchor: "",
  },

  // ─── Profile ────────────────────────────────────────────────────────────────
  {
    sectionId: "profile",
    heading: "Profile Overview",
    keywords: [
      "profile",
      "account",
      "callsign",
      "identity",
      "rank",
      "badges",
      "statistics",
      "public",
      "share",
    ],
    anchor: "",
  },
  {
    sectionId: "profile",
    heading: "Profile Card",
    keywords: [
      "profile card",
      "callsign",
      "grid",
      "bio",
      "avatar",
      "station identity",
      "qr code",
      "completeness",
    ],
    anchor: "profile-card",
  },
  {
    sectionId: "profile",
    heading: "Avatar / Profile Photo",
    keywords: [
      "avatar",
      "photo",
      "image",
      "upload",
      "pro",
      "initials",
      "profile picture",
    ],
    anchor: "profile-card",
  },
  {
    sectionId: "profile",
    heading: "QR Code",
    keywords: ["qr code", "scan", "share", "profile link"],
    anchor: "profile-card",
  },
  {
    sectionId: "profile",
    heading: "Operator Rank System",
    keywords: [
      "rank",
      "system",
      "xp",
      "rp",
      "rank points",
      "novice",
      "apprentice",
      "journeyman",
      "expert",
      "master",
      "legendary",
      "ethereal",
    ],
    anchor: "rank-system",
  },
  {
    sectionId: "profile",
    heading: "Rank Tiers",
    keywords: [
      "rank",
      "tier",
      "novice",
      "apprentice",
      "journeyman",
      "expert",
      "master",
      "legendary",
      "ethereal",
      "rp threshold",
    ],
    anchor: "rank-system",
  },
  {
    sectionId: "profile",
    heading: "RP Sources (How to Earn)",
    keywords: [
      "rp",
      "earn",
      "points",
      "achievements",
      "qso",
      "dxcc",
      "band-mode",
      "contests",
      "login streak",
      "equipment",
      "signal paths",
      "profile complete",
      "shares",
      "elmer",
    ],
    anchor: "rank-system",
  },
  {
    sectionId: "profile",
    heading: "Card Customization",
    keywords: [
      "card",
      "customization",
      "background",
      "particles",
      "tilt",
      "sound",
      "signature",
      "schematic",
      "topographic",
      "circuit",
      "constellation",
      "aurora",
      "living signal",
    ],
    anchor: "rank-system",
  },
  {
    sectionId: "profile",
    heading: "Badges & Awards",
    keywords: [
      "badges",
      "awards",
      "achievement",
      "bronze",
      "silver",
      "gold",
      "platinum",
      "earned",
      "milestones",
    ],
    anchor: "badges",
  },
  {
    sectionId: "profile",
    heading: "Achievement Tiers",
    keywords: [
      "achievement",
      "tier",
      "bronze",
      "silver",
      "gold",
      "platinum",
      "50 rp",
      "100 rp",
      "200 rp",
      "500 rp",
    ],
    anchor: "badges",
  },
  {
    sectionId: "profile",
    heading: "Badge Categories",
    keywords: [
      "badge",
      "category",
      "operating milestones",
      "band achievements",
      "mode achievements",
      "social achievements",
    ],
    anchor: "badges",
  },
  {
    sectionId: "profile",
    heading: "Statistics",
    keywords: [
      "statistics",
      "stats",
      "qso counts",
      "band breakdown",
      "mode breakdown",
      "countries worked",
      "states worked",
      "login streak",
      "longest streak",
      "rank points",
    ],
    anchor: "statistics",
  },
  {
    sectionId: "profile",
    heading: "QSL Cards",
    keywords: [
      "qsl",
      "card",
      "digital",
      "lotw",
      "eqsl",
      "clublog",
      "qrz",
      "confirmation",
      "service",
    ],
    anchor: "qsl-cards",
  },
  {
    sectionId: "profile",
    heading: "Public Profiles",
    keywords: [
      "public",
      "profile",
      "view",
      "other operators",
      "follow",
      "following",
      "privacy",
      "visibility",
    ],
    anchor: "public-profiles",
  },
  {
    sectionId: "profile",
    heading: "Following Operators",
    keywords: ["follow", "following", "friends", "one-directional", "social"],
    anchor: "public-profiles",
  },
  {
    sectionId: "profile",
    heading: "Privacy Controls",
    keywords: [
      "privacy",
      "controls",
      "visibility",
      "location",
      "statistics",
      "activity",
      "public",
      "private",
    ],
    anchor: "public-profiles",
  },
  {
    sectionId: "profile",
    heading: "Completeness Indicator",
    keywords: [
      "completeness",
      "indicator",
      "percentage",
      "profile fields",
      "callsign",
      "grid",
      "name",
      "bio",
      "license",
      "equipment",
      "avatar",
      "100%",
      "100 rp",
    ],
    anchor: "completeness",
  },
  {
    sectionId: "profile",
    heading: "Overview Tab",
    keywords: [
      "overview",
      "tab",
      "station identity",
      "license card",
      "bio",
      "social links",
      "equipment summary",
      "qrz",
      "hamqth",
    ],
    anchor: "overview-tab",
  },
  {
    sectionId: "profile",
    heading: "Station Identity",
    keywords: [
      "station",
      "identity",
      "callsign",
      "operator name",
      "grid square",
      "inline edit",
    ],
    anchor: "overview-tab",
  },
  {
    sectionId: "profile",
    heading: "License Card",
    keywords: [
      "license",
      "card",
      "class",
      "history",
      "timeline",
      "upgrade",
      "technician",
      "general",
      "extra",
    ],
    anchor: "overview-tab",
  },
  {
    sectionId: "profile",
    heading: "Social Links",
    keywords: [
      "social",
      "links",
      "qrz",
      "hamqth",
      "custom links",
      "auto-generated",
    ],
    anchor: "overview-tab",
  },
  {
    sectionId: "profile",
    heading: "Social Tab",
    keywords: [
      "social",
      "tab",
      "friends",
      "activity feed",
      "visibility settings",
      "share card",
    ],
    anchor: "social-tab",
  },
  {
    sectionId: "profile",
    heading: "Friends List",
    keywords: [
      "friends",
      "list",
      "followed",
      "operators",
      "callsign",
      "grid",
      "activity",
    ],
    anchor: "social-tab",
  },
  {
    sectionId: "profile",
    heading: "Activity Feed",
    keywords: [
      "activity",
      "feed",
      "timeline",
      "events",
      "qso",
      "achievements",
      "rank-ups",
    ],
    anchor: "social-tab",
  },
  {
    sectionId: "profile",
    heading: "Share Card",
    keywords: ["share", "card", "image", "social media", "qsl", "generate"],
    anchor: "social-tab",
  },
  {
    sectionId: "profile",
    heading: "FAQ: How do I earn XP (Rank Points)?",
    keywords: [
      "xp",
      "rp",
      "earn",
      "rank points",
      "qso",
      "dxcc",
      "streak",
      "achievements",
      "equipment",
    ],
    anchor: "",
  },
  {
    sectionId: "profile",
    heading: "FAQ: Can other people see my profile?",
    keywords: [
      "see",
      "profile",
      "public",
      "visibility",
      "privacy",
      "other people",
      "callsign",
    ],
    anchor: "",
  },
  {
    sectionId: "profile",
    heading: "FAQ: How do I upload a profile photo?",
    keywords: [
      "upload",
      "photo",
      "profile",
      "avatar",
      "pro",
      "jpg",
      "png",
      "webp",
    ],
    anchor: "",
  },
];
