import { act, cleanup, renderHook } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { useHomeLocation } from "./useHomeLocation";
import { HomeLocationProvider } from "@/components/home/HomeLocationProvider";
const state=vi.hoisted(()=>({authenticated:false}));
vi.mock("@/lib/supabase",()=>({isSupabaseConfigured:true}));
vi.mock("@/stores/authStore",()=>({selectIsAuthenticated:()=>state.authenticated,useAuthStore:()=>state.authenticated}));
vi.mock("@/hooks/useStationCastContext",()=>({useStationCastContext:()=>({location:{grid:"DM79",lat:39.5,lon:-105},chain:null})}));
afterEach(()=>{cleanup();localStorage.removeItem("propulse-home-location-v1");state.authenticated=false;});
it("does not display a cached station location to an unauthenticated visitor",()=>{const {result}=renderHook(()=>useHomeLocation(),{wrapper:HomeLocationProvider});expect(result.current.location).toBeNull();act(()=>result.current.choose("IO91"));expect(result.current.location?.grid).toBe("IO91");act(()=>result.current.choose("global"));expect(result.current.location).toBeNull();});
it("follows the station by default and preserves an explicit Home override",()=>{state.authenticated=true;const {result}=renderHook(()=>useHomeLocation(),{wrapper:HomeLocationProvider});expect(result.current.location?.grid).toBe("DM79");act(()=>result.current.choose("IO91"));expect(result.current.location?.grid).toBe("IO91");act(()=>result.current.choose("station"));expect(result.current.location?.grid).toBe("DM79");});
it("rejects a corrupt persisted location instead of inventing coordinates",()=>{localStorage.setItem("propulse-home-location-v1","ZZ99");const {result}=renderHook(()=>useHomeLocation(),{wrapper:HomeLocationProvider});expect(result.current.location).toBeNull();});
