/**
 * Hook for computing weighted profile completeness score.
 * Returns a 0-100 score, tier label, tier color, and per-item breakdown.
 */

import { useProfileStore } from "@/stores/profileStore";
import { useShackStore } from "@/stores/shackStore";
import { useStationQsoIndex } from "@/hooks/useStationQsoIndex";

interface CompletenessResult {
  score: number; // 0-100
  tier: "Getting Started" | "Good Progress" | "Strong Profile" | "All-Star";
  tierColor: string; // Tailwind color class
  items: { label: string; complete: boolean; weight: number }[];
}

const WEIGHTS = {
  callsign: 22,
  name: 11,
  grid: 17,
  license: 17,
  bio: 5,
  socialLink: 6,
  radio: 11,
  expiration: 5,
  timezone: 6,
};

export function useProfileCompleteness(): CompletenessResult {
  const station = useProfileStore((s) => s.station);
  const license = useProfileStore((s) => s.license);
  const bio = useProfileStore((s) => s.bio);
  const socialLinks = useProfileStore((s) => s.socialLinks);
  const radios = useShackStore((s) => s.radios);
  const { qsoCountById, stampedQsoCount } = useStationQsoIndex();
  const radioComplete =
    stampedQsoCount === 0
      ? radios.length > 0
      : radios.some((radio) => (qsoCountById[radio.id] ?? 0) > 0);

  const items = [
    {
      label: "Callsign",
      complete: !!station?.callsign,
      weight: WEIGHTS.callsign,
    },
    {
      label: "Name",
      complete: !!station?.operatorName,
      weight: WEIGHTS.name,
    },
    { label: "Grid", complete: !!station?.grid, weight: WEIGHTS.grid },
    { label: "License", complete: !!license?.class, weight: WEIGHTS.license },
    { label: "Bio", complete: bio.length > 0, weight: WEIGHTS.bio },
    {
      label: "Social Link",
      complete: socialLinks.some((l) => !l.autoGenerated),
      weight: WEIGHTS.socialLink,
    },
    { label: "Radio", complete: radioComplete, weight: WEIGHTS.radio },
    {
      label: "License Expiration",
      complete: !!license?.expirationDate,
      weight: WEIGHTS.expiration,
    },
    {
      label: "Timezone",
      complete: !!station?.timezone,
      weight: WEIGHTS.timezone,
    },
  ];

  const earned = items
    .filter((i) => i.complete)
    .reduce((sum, i) => sum + i.weight, 0);
  const total = items.reduce((sum, i) => sum + i.weight, 0);
  const score = Math.round((earned / total) * 100);

  const tier =
    score >= 90
      ? "All-Star"
      : score >= 70
        ? "Strong Profile"
        : score >= 40
          ? "Good Progress"
          : "Getting Started";
  const tierColor =
    score >= 90
      ? "text-signal-green"
      : score >= 70
        ? "text-plasma-orange"
        : score >= 40
          ? "text-caution-yellow"
          : "text-gray-400";

  return { score, tier, tierColor, items };
}
