/**
 * useRankAssets — Resolves static visual assets for the operator's rank tier.
 *
 * Fetches the manifest generated by `npm run rank:manifest` and returns
 * typed asset URLs (or null) for the given rank. Multiple variants per
 * slot are supported — the hook picks one at random (stable per mount).
 *
 * Usage:
 *   const assets = useRankAssets(rank);
 *   // assets.profileBackground  → "/assets/rank/ethereal/profile-background/640x960/aurora-nebula.png"
 *   // assets.equipmentCardBg    → null  (no asset yet)
 */

import { useEffect, useMemo, useRef, useState } from "react";
import type { RankTier } from "@/types/rank";

// ─── Manifest shape (matches generate-rank-manifest.mjs output) ─────────────

interface AssetSlot {
  resolution: string | null;
  files: string[];
}

interface ManifestData {
  generated: string;
  tiers: Record<string, Record<string, AssetSlot>>;
}

// ─── Public return type ─────────────────────────────────────────────────────

export interface RankAssets {
  profileBackground: string | null;
  profileCardBg: string | null;
  equipmentCardBg: string | null;
  equipmentCardMdBg: string | null;
  shackPageBg: string | null;
  shareCardBg: string | null;
  qrCardBg: string | null;
  avatarFrame: string | null;
}

const EMPTY_ASSETS: RankAssets = {
  profileBackground: null,
  profileCardBg: null,
  equipmentCardBg: null,
  equipmentCardMdBg: null,
  shackPageBg: null,
  shareCardBg: null,
  qrCardBg: null,
  avatarFrame: null,
};

// Map from RankAssets key to folder name in the asset tree
const SLOT_TO_FOLDER: Record<keyof RankAssets, string> = {
  profileBackground: "profile-background",
  profileCardBg: "profile-card-bg",
  equipmentCardBg: "equipment-card-bg",
  equipmentCardMdBg: "equipment-card-md-bg",
  shackPageBg: "shack-page-bg",
  shareCardBg: "share-card-bg",
  qrCardBg: "qr-card-bg",
  avatarFrame: "avatar-frame",
};

// ─── Module-level manifest cache ────────────────────────────────────────────

let manifestCache: ManifestData | null = null;
let manifestPromise: Promise<ManifestData | null> | null = null;

async function fetchManifest(): Promise<ManifestData | null> {
  if (manifestCache) return manifestCache;
  if (manifestPromise) return manifestPromise;

  manifestPromise = fetch("/assets/rank/manifest.json")
    .then((res) => {
      if (!res.ok) return null;
      return res.json() as Promise<ManifestData>;
    })
    .then((data) => {
      manifestCache = data;
      return data;
    })
    .catch(() => {
      manifestPromise = null; // Allow retry on failure
      return null;
    });

  return manifestPromise;
}

// ─── Pick a stable random file from an array ────────────────────────────────

function pickStable(files: string[], seed: number): string {
  return files[seed % files.length];
}

// ─── Hook ───────────────────────────────────────────────────────────────────

export function useRankAssets(rank: RankTier): RankAssets {
  const [manifest, setManifest] = useState<ManifestData | null>(manifestCache);

  // Stable random seed per mount so the chosen variant doesn't jump on re-render
  const seedRef = useRef(Math.floor(Math.random() * 10000));

  useEffect(() => {
    if (manifest) return;
    let cancelled = false;
    fetchManifest().then((data) => {
      if (!cancelled && data) setManifest(data);
    });
    return () => {
      cancelled = true;
    };
  }, [manifest]);

  return useMemo(() => {
    if (!manifest) return EMPTY_ASSETS;

    const tierData = manifest.tiers[rank];
    if (!tierData) return EMPTY_ASSETS;

    const seed = seedRef.current;
    const result = { ...EMPTY_ASSETS };

    for (const [key, folder] of Object.entries(SLOT_TO_FOLDER)) {
      const slot = tierData[folder];
      if (!slot || slot.files.length === 0) continue;

      const file = pickStable(slot.files, seed);
      const resSegment = slot.resolution ? `/${slot.resolution}` : "";
      result[key as keyof RankAssets] =
        `/assets/rank/${rank}/${folder}${resSegment}/${file}`;
    }

    return result;
  }, [manifest, rank]);
}

/**
 * Invalidate the cached manifest so the next useRankAssets mount re-fetches.
 * Call this after running `npm run rank:manifest` in dev.
 */
export function invalidateRankManifest(): void {
  manifestCache = null;
  manifestPromise = null;
}
