/**
 * Zustand store for user profile, station, and saved targets
 * Decomposed from the monolithic userStore.ts
 * Persists to localStorage with key 'propulse-profile'
 */

import { create } from "zustand";
import { persist, createJSONStorage } from "zustand/middleware";
import type {
  UserStation,
  OperatingLocation,
  LocationType,
  LicenseInfo,
  LicenseClass,
  SocialLink,
} from "@/types/user";
import type { VisibilitySettings } from "@/types/social";
import { DEFAULT_VISIBILITY } from "@/types/social";

import { useSettingsStore } from "./settingsStore";
import { deleteImage } from "@/lib/db/imageStore";

// ─── Types ───────────────────────────────────────────────────────────────────

/**
 * A single entry in the license upgrade history timeline
 */
export interface LicenseHistoryEntry {
  id: string;
  date: string; // ISO date
  class: string; // license class at that point
  notes?: string;
}

/**
 * Saved target location for quick access
 */
export interface SavedTarget {
  id: string;
  name: string;
  lat: number;
  lon: number;
  grid?: string;
  createdAt: string;
}

/**
 * Credentials for QSL confirmation services
 */
export interface ServiceCredentials {
  eqsl?: { username: string; password: string };
  clublog?: { email: string; password: string; callsign: string };
  qrz?: { apiKey: string };
  lotw?: { enabled: boolean };
}

// ─── Constants ───────────────────────────────────────────────────────────────

/** Maximum number of saved targets allowed */
const MAX_SAVED_TARGETS = 10;

// ─── Store interface ─────────────────────────────────────────────────────────

interface ProfileStore {
  station: UserStation | null;
  savedTargets: SavedTarget[];
  serviceCredentials: ServiceCredentials;
  license: LicenseInfo | undefined;
  licenseHistory: LicenseHistoryEntry[];
  bio: string;
  profileImageUrl: string;
  /** UUID referencing a stored profile image in IndexedDB */
  profileImageId: string | undefined;
  lastIngestedCallsign: string;
  socialLinks: SocialLink[];
  visibilitySettings: VisibilitySettings;

  setStation: (station: UserStation | null) => void;
  setBio: (bio: string) => void;
  setProfileImageUrl: (url: string) => void;
  setProfileImageId: (imageId: string | undefined) => void;
  setLastIngestedCallsign: (callsign: string) => void;
  setSocialLinks: (links: SocialLink[]) => void;

  // Location management
  addLocation: (
    location: Omit<OperatingLocation, "id" | "createdAt">,
  ) => string;
  updateLocation: (
    id: string,
    updates: Partial<Omit<OperatingLocation, "id" | "createdAt">>,
  ) => void;
  removeLocation: (id: string) => void;
  setActiveLocation: (id: string | null) => void;
  setTemporaryLocation: (
    grid: string,
    lat: number,
    lon: number,
    name?: string,
    type?: LocationType,
  ) => string;
  clearTemporaryLocation: () => void;

  // Targets
  addTarget: (target: Omit<SavedTarget, "id" | "createdAt">) => void;
  removeTarget: (id: string) => void;
  clearTargets: () => void;

  // Credentials
  setServiceCredentials: (creds: Partial<ServiceCredentials>) => void;

  // License
  setLicense: (license: LicenseInfo | null) => void;

  // Visibility
  setVisibilitySettings: (updates: Partial<VisibilitySettings>) => void;

  // License history
  addLicenseHistoryEntry: (entry: LicenseHistoryEntry) => void;
  removeLicenseHistoryEntry: (id: string) => void;
}

// ─── Store ───────────────────────────────────────────────────────────────────

export const useProfileStore = create<ProfileStore>()(
  persist(
    (set) => ({
      station: null,
      savedTargets: [],
      serviceCredentials: {},
      license: undefined,
      licenseHistory: [],
      bio: "",
      profileImageUrl: "",
      profileImageId: undefined,
      lastIngestedCallsign: "",
      socialLinks: [],
      visibilitySettings: { ...DEFAULT_VISIBILITY },

      setStation: (station) =>
        set((state) => {
          // Auto-generate social links when callsign changes
          if (
            station?.callsign &&
            station.callsign !== state.station?.callsign
          ) {
            const callsign = station.callsign.toUpperCase();
            const autoLinks: SocialLink[] = [
              {
                type: "qrz",
                url: `https://www.qrz.com/db/${callsign}`,
                autoGenerated: true,
              },
              {
                type: "hamqth",
                url: `https://www.hamqth.com/${callsign}`,
                autoGenerated: true,
              },
            ];
            // Keep user's manual links, replace auto-generated ones
            const manualLinks = state.socialLinks.filter(
              (l) => !l.autoGenerated,
            );
            return { station, socialLinks: [...autoLinks, ...manualLinks] };
          }
          return { station };
        }),

      setBio: (bio) => set({ bio }),
      setProfileImageUrl: (url) => set({ profileImageUrl: url }),
      setProfileImageId: (imageId) =>
        set((state) => {
          // Delete the old blob from IndexedDB if replacing or clearing
          if (state.profileImageId && state.profileImageId !== imageId) {
            deleteImage(state.profileImageId).catch(() => {
              /* best-effort cleanup */
            });
          }
          return { profileImageId: imageId };
        }),
      setLastIngestedCallsign: (callsign) =>
        set({ lastIngestedCallsign: callsign }),
      setSocialLinks: (links) => set({ socialLinks: links }),

      // === Location Management ===

      addLocation: (location) => {
        const id = crypto.randomUUID();
        const newLocation: OperatingLocation = {
          ...location,
          id,
          createdAt: new Date().toISOString(),
        };

        set((state) => {
          if (!state.station) return state;

          const savedLocations = [...state.station.savedLocations, newLocation];

          return {
            station: { ...state.station, savedLocations },
          };
        });

        return id;
      },

      updateLocation: (id, updates) =>
        set((state) => {
          if (!state.station) return state;

          const savedLocations = state.station.savedLocations.map((loc) =>
            loc.id === id ? { ...loc, ...updates } : loc,
          );

          const activeId =
            state.station.activeLocationId ?? state.station.homeLocationId;
          const updatedLocation = savedLocations.find((loc) => loc.id === id);

          if (updatedLocation && id === activeId) {
            return {
              station: {
                ...state.station,
                savedLocations,
                grid: updatedLocation.grid,
                lat: updatedLocation.lat,
                lon: updatedLocation.lon,
                timezone: updatedLocation.timezone,
              },
            };
          }

          return { station: { ...state.station, savedLocations } };
        }),

      removeLocation: (id) =>
        set((state) => {
          if (!state.station) return state;
          if (id === state.station.homeLocationId) return state;

          const savedLocations = state.station.savedLocations.filter(
            (loc) => loc.id !== id,
          );

          const activeLocationId =
            state.station.activeLocationId === id
              ? null
              : state.station.activeLocationId;

          if (
            state.station.activeLocationId === id &&
            activeLocationId === null
          ) {
            const homeLocation = savedLocations.find(
              (loc) => loc.id === state.station!.homeLocationId,
            );
            if (homeLocation) {
              return {
                station: {
                  ...state.station,
                  savedLocations,
                  activeLocationId,
                  grid: homeLocation.grid,
                  lat: homeLocation.lat,
                  lon: homeLocation.lon,
                  timezone: homeLocation.timezone,
                },
              };
            }
          }

          return {
            station: { ...state.station, savedLocations, activeLocationId },
          };
        }),

      setActiveLocation: (id) =>
        set((state) => {
          if (!state.station) return state;

          const targetId = id ?? state.station.homeLocationId;
          const location = state.station.savedLocations.find(
            (loc) => loc.id === targetId,
          );
          if (!location) return state;

          return {
            station: {
              ...state.station,
              activeLocationId: id,
              grid: location.grid,
              lat: location.lat,
              lon: location.lon,
              timezone: location.timezone,
            },
          };
        }),

      setTemporaryLocation: (grid, lat, lon, name, type) => {
        const id = crypto.randomUUID();
        const newLocation: OperatingLocation = {
          id,
          name: name ?? "Temporary",
          grid,
          lat,
          lon,
          type: type ?? "portable",
          createdAt: new Date().toISOString(),
        };

        set((state) => {
          if (!state.station) return state;

          const savedLocations = [...state.station.savedLocations, newLocation];

          return {
            station: {
              ...state.station,
              savedLocations,
              activeLocationId: id,
              grid,
              lat,
              lon,
            },
          };
        });

        return id;
      },

      clearTemporaryLocation: () =>
        set((state) => {
          if (!state.station) return state;

          const homeLocation = state.station.savedLocations.find(
            (loc) => loc.id === state.station!.homeLocationId,
          );
          if (!homeLocation) return state;

          return {
            station: {
              ...state.station,
              activeLocationId: null,
              grid: homeLocation.grid,
              lat: homeLocation.lat,
              lon: homeLocation.lon,
              timezone: homeLocation.timezone,
            },
          };
        }),

      // === Targets ===

      addTarget: (target) =>
        set((state) => {
          const newTarget: SavedTarget = {
            ...target,
            id: crypto.randomUUID(),
            createdAt: new Date().toISOString(),
          };
          const updated = [newTarget, ...state.savedTargets];
          if (updated.length > MAX_SAVED_TARGETS) {
            updated.pop();
          }
          return { savedTargets: updated };
        }),

      removeTarget: (id) =>
        set((state) => ({
          savedTargets: state.savedTargets.filter((t) => t.id !== id),
        })),

      clearTargets: () => set({ savedTargets: [] }),

      // === Credentials ===

      setServiceCredentials: (creds) =>
        set((state) => {
          const serviceCredentials: ServiceCredentials = {
            ...state.serviceCredentials,
          };

          for (const key of Object.keys(creds) as Array<
            keyof ServiceCredentials
          >) {
            const incoming = creds[key];
            if (incoming === undefined) {
              serviceCredentials[key] = undefined;
              continue;
            }

            const previous = state.serviceCredentials[key];
            serviceCredentials[key] = {
              ...(previous ? (previous as Record<string, unknown>) : {}),
              ...(incoming as Record<string, unknown>),
            } as never;
          }

          return { serviceCredentials };
        }),

      // === License ===

      setLicense: (license) =>
        set(() => {
          // Cross-store side effect: sync licenseClass to settingsStore
          const currentClass = useSettingsStore.getState().licenseClass;
          useSettingsStore
            .getState()
            .setLicenseClass(
              license?.class ?? currentClass ?? ("GENERAL" as LicenseClass),
            );

          return { license: license ?? undefined };
        }),

      // === Visibility ===

      setVisibilitySettings: (updates) =>
        set((state) => ({
          visibilitySettings: { ...state.visibilitySettings, ...updates },
        })),

      // === License History ===

      addLicenseHistoryEntry: (entry) =>
        set((state) => ({
          licenseHistory: [...state.licenseHistory, entry].slice(-10),
        })),

      removeLicenseHistoryEntry: (id) =>
        set((state) => ({
          licenseHistory: state.licenseHistory.filter((e) => e.id !== id),
        })),
    }),
    {
      name: "propulse-profile",
      version: 6,
      storage: createJSONStorage(() => localStorage),
      partialize: (state) => ({
        station: state.station,
        savedTargets: state.savedTargets,
        license: state.license,
        licenseHistory: state.licenseHistory,
        bio: state.bio,
        profileImageUrl: state.profileImageUrl,
        profileImageId: state.profileImageId,
        lastIngestedCallsign: state.lastIngestedCallsign,
        socialLinks: state.socialLinks,
        // NOTE: serviceCredentials intentionally excluded — use credentialStore (encrypted IDB) instead
        visibilitySettings: state.visibilitySettings,
      }),
      migrate: (persisted: unknown, version: number) => {
        const state = persisted as Record<string, unknown>;
        if (version < 2) {
          if (!("bio" in state)) state.bio = "";
          if (!("socialLinks" in state)) state.socialLinks = [];
        }
        if (version < 3) {
          if (!("licenseHistory" in state)) state.licenseHistory = [];
        }
        if (version < 4) {
          if (!("profileImageUrl" in state)) state.profileImageUrl = "";
          if (!("serviceCredentials" in state)) state.serviceCredentials = {};
        }
        if (version < 5) {
          if (!("visibilitySettings" in state))
            state.visibilitySettings = { ...DEFAULT_VISIBILITY };
        }
        if (version < 6) {
          if (!("profileImageId" in state)) state.profileImageId = undefined;
        }
        return state as unknown as ProfileStore;
      },
    },
  ),
);
