/**
 * Contest ADIF Import/Export
 *
 * Provides ADIF 3.x format import and export for contest sessions.
 * Supports standard ADIF fields plus contest-specific extensions.
 *
 * @module lib/contest/adif
 */

import type { ContestSession, ContestQSO } from "@/stores/contestStore";
import { getContestById } from "@/lib/data/contests";
import { normalizeBand, normalizeMode } from "./index";

/**
 * Result of importing ADIF content into a contest session
 */
export interface ADIFImportResult {
  /** Successfully imported QSOs */
  importedQSOs: ContestQSO[];
  /** Number of records successfully imported */
  importedCount: number;
  /** Number of records that failed to import */
  failedCount: number;
  /** Number of records skipped (e.g., duplicates) */
  skippedCount: number;
  /** Warnings generated during import */
  warnings: ADIFImportWarning[];
  /** Errors that prevented import of specific records */
  errors: ADIFImportError[];
}

/**
 * Warning generated during ADIF import
 */
export interface ADIFImportWarning {
  /** Record number (1-based) */
  recordNumber: number;
  /** Callsign if available */
  callsign?: string;
  /** Warning message */
  message: string;
  /** Field that caused the warning */
  field?: string;
}

/**
 * Error that prevented import of a record
 */
export interface ADIFImportError {
  /** Record number (1-based) */
  recordNumber: number;
  /** Callsign if available */
  callsign?: string;
  /** Error message */
  message: string;
  /** Field that caused the error */
  field?: string;
}

/**
 * Options for ADIF export
 */
export interface ADIFExportOptions {
  /** Include ADIF file header (default: true) */
  includeHeader?: boolean;
  /** Include contest-specific APP_PROPULSE_* fields (default: true) */
  includeAppFields?: boolean;
  /** Program ID for header (default: "ProPulse") */
  programId?: string;
  /** Program version for header (default: "1.0.0") */
  programVersion?: string;
}

/**
 * Parsed ADIF field with name, length, and value
 */
interface ParsedADIFField {
  name: string;
  length: number;
  type?: string;
  value: string;
}

/**
 * Format a single ADIF field
 */
function formatADIFField(
  name: string,
  value: string | number | undefined,
): string {
  if (value === undefined || value === null || value === "") return "";
  const strValue = String(value);
  return `<${name}:${strValue.length}>${strValue}`;
}

/**
 * Generate ADIF header
 */
function generateADIFHeader(options: ADIFExportOptions): string {
  const lines: string[] = [];
  const programId = options.programId || "ProPulse";
  const programVersion = options.programVersion || "1.0.0";
  const timestamp = new Date().toISOString().replace(/[-:T]/g, "").slice(0, 14);

  lines.push("Generated by ProPulse Contest Mode");
  lines.push(`<ADIF_VER:5>3.1.4`);
  lines.push(`<CREATED_TIMESTAMP:14>${timestamp}`);
  lines.push(`<PROGRAMID:${programId.length}>${programId}`);
  lines.push(`<PROGRAMVERSION:${programVersion.length}>${programVersion}`);
  lines.push("<EOH>");
  lines.push("");

  return lines.join("\n");
}

/**
 * Convert ISO date (YYYY-MM-DD or YYYY-MM-DDTHH:MM:SS) to ADIF date (YYYYMMDD)
 */
function isoToADIFDate(isoDate: string): string {
  return isoDate.slice(0, 10).replace(/-/g, "");
}

/**
 * Convert ISO timestamp to ADIF time (HHMM or HHMMSS)
 */
function isoToADIFTime(isoTimestamp: string, includeSeconds = false): string {
  const timePart = isoTimestamp.includes("T")
    ? isoTimestamp.split("T")[1]
    : "0000";
  const cleaned = timePart.replace(/:/g, "").slice(0, includeSeconds ? 6 : 4);
  return cleaned.padEnd(includeSeconds ? 6 : 4, "0");
}

/**
 * Convert ADIF date (YYYYMMDD) to ISO date (YYYY-MM-DD)
 */
function adifToISODate(adifDate: string): string {
  if (adifDate.length !== 8) return adifDate;
  return `${adifDate.slice(0, 4)}-${adifDate.slice(4, 6)}-${adifDate.slice(6, 8)}`;
}

/**
 * Convert ADIF time (HHMM or HHMMSS) to HH:MM:SS format
 */
function adifToISOTime(adifTime: string): string {
  const padded = adifTime.padEnd(6, "0");
  return `${padded.slice(0, 2)}:${padded.slice(2, 4)}:${padded.slice(4, 6)}`;
}

/**
 * Get frequency in kHz from band string
 * Returns approximate band center frequency
 */
function bandToFrequencyKHz(band: string): number {
  const bandMap: Record<string, number> = {
    "160m": 1850,
    "80m": 3550,
    "60m": 5330,
    "40m": 7050,
    "30m": 10125,
    "20m": 14100,
    "17m": 18100,
    "15m": 21100,
    "12m": 24900,
    "10m": 28300,
    "6m": 50100,
    "2m": 144100,
    "70cm": 432100,
  };
  return bandMap[band.toLowerCase()] || 0;
}

/**
 * Get band from frequency in kHz
 */
function frequencyToBand(freqKHz: number): string {
  if (freqKHz >= 1800 && freqKHz <= 2000) return "160m";
  if (freqKHz >= 3500 && freqKHz <= 4000) return "80m";
  if (freqKHz >= 5250 && freqKHz <= 5450) return "60m";
  if (freqKHz >= 7000 && freqKHz <= 7300) return "40m";
  if (freqKHz >= 10100 && freqKHz <= 10150) return "30m";
  if (freqKHz >= 14000 && freqKHz <= 14350) return "20m";
  if (freqKHz >= 18068 && freqKHz <= 18168) return "17m";
  if (freqKHz >= 21000 && freqKHz <= 21450) return "15m";
  if (freqKHz >= 24890 && freqKHz <= 24990) return "12m";
  if (freqKHz >= 28000 && freqKHz <= 29700) return "10m";
  if (freqKHz >= 50000 && freqKHz <= 54000) return "6m";
  if (freqKHz >= 144000 && freqKHz <= 148000) return "2m";
  if (freqKHz >= 420000 && freqKHz <= 450000) return "70cm";
  return "20m"; // Default fallback
}

/**
 * Convert frequency in MHz (ADIF FREQ field) to kHz
 */
function freqMHzToKHz(freqMHz: string): number {
  const mhz = parseFloat(freqMHz);
  return isNaN(mhz) ? 0 : Math.round(mhz * 1000);
}

/**
 * Convert frequency in kHz to MHz string for ADIF
 */
function freqKHzToMHz(freqKHz: number): string {
  return (freqKHz / 1000).toFixed(6);
}

/**
 * Map ADIF mode to contest mode
 */
function mapADIFModeToContest(adifMode: string): string {
  const mode = adifMode.toUpperCase();

  // Phone modes
  if (["SSB", "USB", "LSB", "AM", "FM", "PHONE"].includes(mode)) {
    return "SSB";
  }

  // CW
  if (mode === "CW") {
    return "CW";
  }

  // Digital modes
  if (
    [
      "RTTY",
      "PSK31",
      "PSK63",
      "PSK",
      "FT8",
      "FT4",
      "JT65",
      "JT9",
      "JS8",
      "MFSK",
      "OLIVIA",
      "DATA",
      "DIGITAL",
    ].includes(mode)
  ) {
    return "RTTY";
  }

  return mode;
}

/**
 * Map contest mode to ADIF mode
 */
function mapContestModeToADIF(contestMode: string): string {
  const mode = contestMode.toUpperCase();
  if (mode === "DIGITAL" || mode === "DIGI") return "RTTY";
  return mode;
}

/**
 * Parse a single ADIF field from content
 */
function parseADIFField(
  content: string,
): { field: ParsedADIFField; remaining: string } | null {
  const headerMatch = content.match(/^<([A-Za-z0-9_]+):(\d+)(?::([A-Z]))?>/i);

  if (!headerMatch) {
    return null;
  }

  const [fullMatch, name, lengthStr, type] = headerMatch;
  const length = parseInt(lengthStr, 10);
  const valueStart = fullMatch.length;
  const value = content.slice(valueStart, valueStart + length);
  const remaining = content.slice(valueStart + length);

  return {
    field: {
      name: name.toUpperCase(),
      length,
      type,
      value,
    },
    remaining,
  };
}

/**
 * Parse ADIF content into an array of field maps
 */
function parseADIFToRecords(adifContent: string): Map<string, string>[] {
  const records: Map<string, string>[] = [];
  let content = adifContent;

  // Skip the header section if present
  const eohIndex = content.toUpperCase().indexOf("<EOH>");
  if (eohIndex !== -1) {
    content = content.slice(eohIndex + 5).trimStart();
  }

  let currentRecord = new Map<string, string>();

  while (content.length > 0) {
    content = content.trimStart();

    if (content.length === 0) {
      break;
    }

    // Check for end of record
    if (content.toUpperCase().startsWith("<EOR>")) {
      if (currentRecord.size > 0) {
        records.push(currentRecord);
        currentRecord = new Map<string, string>();
      }
      content = content.slice(5);
      continue;
    }

    // Check for field start
    if (content.startsWith("<")) {
      const result = parseADIFField(content);
      if (result) {
        currentRecord.set(result.field.name, result.field.value);
        content = result.remaining;
      } else {
        // Skip malformed tag
        const nextTag = content.indexOf("<", 1);
        content = nextTag === -1 ? "" : content.slice(nextTag);
      }
    } else {
      // Skip non-tag content
      const nextTag = content.indexOf("<");
      content = nextTag === -1 ? "" : content.slice(nextTag);
    }
  }

  // Include last record if it didn't end with <EOR>
  if (currentRecord.size > 0) {
    records.push(currentRecord);
  }

  return records;
}

/**
 * Export a single ContestQSO to ADIF record string
 */
function exportQSOToADIF(
  qso: ContestQSO,
  session: ContestSession,
  options: ADIFExportOptions,
): string {
  const fields: string[] = [];

  // Core required fields
  fields.push(formatADIFField("CALL", qso.callsign.toUpperCase()));
  fields.push(formatADIFField("QSO_DATE", isoToADIFDate(qso.timestamp)));
  fields.push(formatADIFField("TIME_ON", isoToADIFTime(qso.timestamp)));

  // Band and frequency
  fields.push(formatADIFField("BAND", qso.band.toUpperCase()));
  if (qso.frequencyKHz && qso.frequencyKHz > 0) {
    fields.push(formatADIFField("FREQ", freqKHzToMHz(qso.frequencyKHz)));
  }

  // Mode
  fields.push(formatADIFField("MODE", mapContestModeToADIF(qso.mode)));

  // RST reports
  fields.push(formatADIFField("RST_SENT", qso.rstSent));
  fields.push(formatADIFField("RST_RCVD", qso.rstReceived));

  // Contest-specific ADIF fields
  const contest = getContestById(session.contestId);
  if (contest) {
    fields.push(formatADIFField("CONTEST_ID", contest.cabrilloId));
  }

  // Serial numbers (standard ADIF fields)
  if (qso.serialSent !== undefined) {
    fields.push(formatADIFField("STX", String(qso.serialSent)));
  }
  if (qso.serialReceived !== undefined) {
    fields.push(formatADIFField("SRX", String(qso.serialReceived)));
  }

  // Exchange as STX_STRING and SRX_STRING
  if (qso.exchangeSent) {
    fields.push(formatADIFField("STX_STRING", qso.exchangeSent));
  }
  if (qso.exchangeReceived) {
    fields.push(formatADIFField("SRX_STRING", qso.exchangeReceived));
  }

  // App-specific fields for ProPulse data preservation
  if (options.includeAppFields !== false) {
    if (qso.isDupe) {
      fields.push(formatADIFField("APP_PROPULSE_DUPE", "Y"));
    }
    if (qso.points !== undefined) {
      fields.push(formatADIFField("APP_PROPULSE_POINTS", String(qso.points)));
    }
    if (qso.isMultiplier) {
      fields.push(formatADIFField("APP_PROPULSE_MULT", "Y"));
    }
    if (qso.multipliers && qso.multipliers.length > 0) {
      fields.push(
        formatADIFField("APP_PROPULSE_MULT_VALUE", qso.multipliers.join(",")),
      );
    }
    if (qso.rawInput) {
      fields.push(formatADIFField("APP_PROPULSE_RAW", qso.rawInput));
    }
  }

  // Filter out empty fields and join
  const validFields = fields.filter((f) => f !== "");
  return validFields.join("") + "<EOR>";
}

/**
 * Export a contest session to ADIF format
 *
 * @param session - The contest session to export
 * @param options - Export options
 * @returns ADIF formatted string
 *
 * @example
 * ```ts
 * const adifContent = exportSessionToADIF(session);
 * downloadADIF(adifContent, 'contest-log.adi');
 * ```
 */
export function exportSessionToADIF(
  session: ContestSession,
  options: ADIFExportOptions = {},
): string {
  const parts: string[] = [];

  // Add header if requested
  if (options.includeHeader !== false) {
    parts.push(generateADIFHeader(options));
  }

  // Export each QSO
  for (const qso of session.qsos) {
    parts.push(exportQSOToADIF(qso, session, options));
    parts.push(""); // Empty line between records for readability
  }

  return parts.join("\n");
}

/**
 * Import ADIF content into ContestQSO array
 *
 * @param adifContent - Raw ADIF file content
 * @param session - Target contest session (for context and validation)
 * @returns Import result with QSOs, warnings, and errors
 *
 * @example
 * ```ts
 * const result = importADIFToSession(adifContent, activeSession);
 * if (result.errors.length === 0) {
 *   // Add QSOs to session
 *   for (const qso of result.importedQSOs) {
 *     store.logQSO(qso);
 *   }
 * }
 * ```
 */
export function importADIFToSession(
  adifContent: string,
  session: ContestSession,
): ADIFImportResult {
  const result: ADIFImportResult = {
    importedQSOs: [],
    importedCount: 0,
    failedCount: 0,
    skippedCount: 0,
    warnings: [],
    errors: [],
  };

  const records = parseADIFToRecords(adifContent);

  // Build set of existing QSO keys to detect duplicates
  const existingKeys = new Set<string>();
  for (const qso of session.qsos) {
    const key = `${qso.callsign.toUpperCase()}|${qso.band.toLowerCase()}|${qso.mode.toUpperCase()}|${isoToADIFDate(qso.timestamp)}`;
    existingKeys.add(key);
  }

  for (let i = 0; i < records.length; i++) {
    const record = records[i];
    const recordNum = i + 1;

    // Extract callsign (required)
    const callsign = record.get("CALL");
    if (!callsign) {
      result.errors.push({
        recordNumber: recordNum,
        message: "Missing required CALL field",
        field: "CALL",
      });
      result.failedCount++;
      continue;
    }

    // Extract date and time
    const qsoDate = record.get("QSO_DATE");
    const timeOn = record.get("TIME_ON");

    if (!qsoDate) {
      result.errors.push({
        recordNumber: recordNum,
        callsign,
        message: "Missing required QSO_DATE field",
        field: "QSO_DATE",
      });
      result.failedCount++;
      continue;
    }

    // Build ISO timestamp
    const isoDate = adifToISODate(qsoDate);
    const isoTime = timeOn ? adifToISOTime(timeOn) : "00:00:00";
    const timestamp = `${isoDate}T${isoTime}Z`;

    // Extract band and mode
    let band = record.get("BAND") || "";
    const mode = record.get("MODE") || record.get("SUBMODE") || "";

    // Try to derive band from frequency if not provided
    const freqStr = record.get("FREQ");
    let frequencyKHz = 0;
    if (freqStr) {
      frequencyKHz = freqMHzToKHz(freqStr);
      if (!band && frequencyKHz > 0) {
        band = frequencyToBand(frequencyKHz);
        result.warnings.push({
          recordNumber: recordNum,
          callsign,
          message: `Band derived from frequency: ${band}`,
          field: "BAND",
        });
      }
    }

    // Validate band
    if (!band) {
      result.errors.push({
        recordNumber: recordNum,
        callsign,
        message: "Missing BAND field and could not derive from FREQ",
        field: "BAND",
      });
      result.failedCount++;
      continue;
    }

    // Validate mode
    if (!mode) {
      result.warnings.push({
        recordNumber: recordNum,
        callsign,
        message: "Missing MODE field, defaulting to CW",
        field: "MODE",
      });
    }

    // Normalize band and mode
    const normalizedBand = normalizeBand(band);
    const normalizedMode = mode
      ? normalizeMode(mapADIFModeToContest(mode))
      : "CW";

    // Check for duplicates
    const dupeKey = `${callsign.toUpperCase()}|${normalizedBand.toLowerCase()}|${normalizedMode.toUpperCase()}|${qsoDate}`;
    if (existingKeys.has(dupeKey)) {
      result.warnings.push({
        recordNumber: recordNum,
        callsign,
        message: "Duplicate QSO skipped (same call/band/mode/date exists)",
      });
      result.skippedCount++;
      continue;
    }

    // Extract RST
    const rstSent = record.get("RST_SENT") || getDefaultRST(normalizedMode);
    const rstReceived = record.get("RST_RCVD") || getDefaultRST(normalizedMode);

    // Extract serials
    const stx = record.get("STX");
    const srx = record.get("SRX");
    const serialSent = stx ? parseInt(stx, 10) : undefined;
    const serialReceived = srx ? parseInt(srx, 10) : undefined;

    // Extract exchange
    const exchangeSent =
      record.get("STX_STRING") || record.get("EXCHANGE") || "";
    const exchangeReceived =
      record.get("SRX_STRING") || record.get("EXCHANGE_RCVD") || "";

    // Extract app-specific fields if present
    const isDupe = record.get("APP_PROPULSE_DUPE") === "Y";
    const isMultiplier = record.get("APP_PROPULSE_MULT") === "Y";
    const pointsStr = record.get("APP_PROPULSE_POINTS");
    const points = pointsStr ? parseInt(pointsStr, 10) : 1;
    const multipliers = record.get("APP_PROPULSE_MULT_VALUE")?.split(",") || [];
    const rawInput = record.get("APP_PROPULSE_RAW");

    // Set frequency from band center if not provided
    if (frequencyKHz === 0) {
      frequencyKHz = bandToFrequencyKHz(normalizedBand);
    }

    // Build ContestQSO
    const qso: ContestQSO = {
      id: crypto.randomUUID(),
      timestamp,
      callsign: callsign.toUpperCase().trim(),
      band: normalizedBand,
      mode: normalizedMode,
      rstSent,
      rstReceived,
      exchangeSent,
      exchangeReceived,
      serialSent,
      serialReceived,
      frequencyKHz,
      points,
      isMultiplier,
      isDupe,
      multipliers: multipliers.length > 0 ? multipliers : undefined,
      rawInput,
    };

    result.importedQSOs.push(qso);
    result.importedCount++;
    existingKeys.add(dupeKey);
  }

  return result;
}

/**
 * Get default RST based on mode
 */
function getDefaultRST(mode: string): string {
  const upperMode = mode.toUpperCase();
  if (
    ["CW", "RTTY", "PSK31", "PSK", "DIGITAL", "DATA", "FT8", "FT4"].includes(
      upperMode,
    )
  ) {
    return "599";
  }
  return "59";
}

/**
 * Validate ADIF content (basic check)
 *
 * @param content - Content to validate
 * @returns True if content appears to be valid ADIF
 */
export function isValidADIF(content: string): boolean {
  if (!content || content.trim().length === 0) {
    return false;
  }

  // Must contain at least one field tag
  const hasTag = /<[A-Za-z0-9_]+:\d+>/i.test(content);

  // Must contain either <EOR> or <EOH>
  const hasMarker =
    content.toUpperCase().includes("<EOR>") ||
    content.toUpperCase().includes("<EOH>");

  return hasTag || hasMarker;
}

/**
 * Get statistics about ADIF content without fully parsing
 *
 * @param content - ADIF content to analyze
 * @returns Object with record count and field summary
 */
export function getADIFStats(content: string): {
  recordCount: number;
  hasHeader: boolean;
  fields: string[];
} {
  const upperContent = content.toUpperCase();

  // Count <EOR> markers for record count
  const eorMatches = upperContent.match(/<EOR>/g);
  const recordCount = eorMatches ? eorMatches.length : 0;

  // Check for header
  const hasHeader = upperContent.includes("<EOH>");

  // Extract unique field names
  const fieldMatches = content.matchAll(/<([A-Za-z0-9_]+):\d+/gi);
  const fields = new Set<string>();
  for (const match of fieldMatches) {
    fields.add(match[1].toUpperCase());
  }

  return {
    recordCount,
    hasHeader,
    fields: Array.from(fields).sort(),
  };
}

/**
 * Download ADIF content as a file
 *
 * @param content - ADIF content string
 * @param filename - Filename for download (default: "contest-log.adi")
 */
export function downloadADIF(
  content: string,
  filename: string = "contest-log.adi",
): void {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
