/**
 * Sporadic E Alert Service
 *
 * Monitors Es detections and generates alerts when openings are detected.
 * Provides a pub/sub interface for UI components to receive notifications.
 *
 * Features:
 * - Priority-based alerts (critical for 6m, high for 10m)
 * - Deduplication: no re-alerts for same region within 30 minutes
 * - Auto-dismiss after 15 minutes with no supporting spots
 * - Listener-based notification system
 *
 * NO React dependencies - pure service module.
 */

import type { EsDetection } from "@/lib/utils/sporadicE";
import { getDistance } from "@/lib/utils/path";

// =============================================================================
// TYPES
// =============================================================================

/** Priority levels for Es alerts */
export type EsAlertPriority = "critical" | "high" | "normal";

/**
 * A sporadic E alert generated by the alert service
 */
export interface EsAlert {
  /** Unique alert identifier */
  id: string;
  /** The Es detection that triggered this alert */
  detection: EsDetection;
  /** Human-readable alert message */
  message: string;
  /** Alert priority level */
  priority: EsAlertPriority;
  /** Timestamp when the alert was created */
  createdAt: number;
  /** Whether the user has dismissed this alert */
  dismissed: boolean;
}

/** Callback type for alert listeners */
export type EsAlertListener = (alert: EsAlert) => void;

// =============================================================================
// CONSTANTS
// =============================================================================

/** Don't re-alert for the same region within this window (ms) */
const DEDUP_WINDOW_MS = 30 * 60 * 1000; // 30 minutes

/** Auto-dismiss alerts with no supporting spots after this time (ms) */
const AUTO_DISMISS_MS = 15 * 60 * 1000; // 15 minutes

/** Maximum distance (km) to consider two detections as the same region */
const SAME_REGION_THRESHOLD_KM = 500;

// =============================================================================
// HELPERS
// =============================================================================

/**
 * Generate a unique alert ID
 */
function generateAlertId(): string {
  const timestamp = Date.now().toString(36);
  const random = Math.random().toString(36).substring(2, 6);
  return `es-${timestamp}-${random}`;
}

/**
 * Determine alert priority based on which bands are active.
 * 6m Es = critical (rare, valuable VHF opening)
 * 10m-only Es = high (enhanced HF conditions)
 */
function getAlertPriority(detection: EsDetection): EsAlertPriority {
  if (detection.bands.includes("6m")) {
    return "critical";
  }
  if (detection.bands.includes("10m")) {
    return "high";
  }
  return "normal";
}

/**
 * Build a descriptive alert message from the detection data.
 */
function buildAlertMessage(detection: EsDetection): string {
  const bandList = detection.bands.join(", ");
  const durationMin = Math.round(detection.duration / 60);
  const region = describeRegion(detection.centerLat, detection.centerLon);

  return (
    `Es opening detected: ${bandList} active ${region}. ` +
    `Estimated MUF > ${detection.estimatedMUFMHz} MHz. ` +
    `${detection.spotCount} spots in ${durationMin > 0 ? `${durationMin} min` : "< 1 min"}.`
  );
}

/**
 * Produce a rough geographic description from lat/lon.
 */
function describeRegion(lat: number, lon: number): string {
  const ns = lat >= 0 ? "N" : "S";
  const ew = lon >= 0 ? "E" : "W";
  return `near ${Math.abs(lat).toFixed(0)}\u00B0${ns}, ${Math.abs(lon).toFixed(0)}\u00B0${ew}`;
}

// =============================================================================
// SERVICE CLASS
// =============================================================================

/**
 * EsAlertService monitors sporadic E detections and manages alerts.
 *
 * Usage:
 * ```ts
 * const service = new EsAlertService();
 * const unsub = service.onAlert((alert) => showNotification(alert));
 * service.checkForAlerts(detection, userLat, userLon);
 * // later...
 * unsub();
 * ```
 */
export class EsAlertService {
  private alerts: EsAlert[] = [];
  private listeners: EsAlertListener[] = [];
  private lastAlertTimestamps: Map<string, number> = new Map();

  /**
   * Check a detection and generate an alert if warranted.
   *
   * Performs deduplication by checking if an alert for the same region
   * was already issued within the dedup window. Also auto-dismisses
   * stale alerts.
   *
   * @param detection - Current Es detection (null if no opening)
   * @param userLat - User's latitude for relevance check
   * @param userLon - User's longitude for relevance check
   */
  checkForAlerts(
    detection: EsDetection | null,
    _userLat: number,
    _userLon: number,
  ): void {
    // Auto-dismiss stale alerts
    this.autoDismissStale();

    if (!detection || !detection.active) {
      return;
    }

    // Check deduplication: don't re-alert for the same region within the window
    if (this.isDuplicate(detection)) {
      return;
    }

    const priority = getAlertPriority(detection);
    const message = buildAlertMessage(detection);

    const alert: EsAlert = {
      id: generateAlertId(),
      detection,
      message,
      priority,
      createdAt: Date.now(),
      dismissed: false,
    };

    this.alerts.push(alert);

    // Record this region for deduplication
    const regionKey = this.getRegionKey(detection);
    this.lastAlertTimestamps.set(regionKey, Date.now());

    // Notify all listeners
    for (const listener of this.listeners) {
      try {
        listener(alert);
      } catch {
        // Don't let a failing listener break the service
      }
    }
  }

  /**
   * Subscribe to new alert notifications.
   *
   * @param callback - Function called when a new alert is generated
   * @returns Unsubscribe function
   */
  onAlert(callback: EsAlertListener): () => void {
    this.listeners.push(callback);

    return () => {
      const index = this.listeners.indexOf(callback);
      if (index >= 0) {
        this.listeners.splice(index, 1);
      }
    };
  }

  /**
   * Get all active (non-dismissed) alerts.
   */
  getActiveAlerts(): EsAlert[] {
    return this.alerts.filter((a) => !a.dismissed);
  }

  /**
   * Dismiss an alert by ID.
   *
   * @param alertId - The alert ID to dismiss
   */
  dismiss(alertId: string): void {
    const alert = this.alerts.find((a) => a.id === alertId);
    if (alert) {
      alert.dismissed = true;
    }
  }

  /**
   * Clear all alerts (for testing or reset).
   */
  clear(): void {
    this.alerts = [];
    this.lastAlertTimestamps.clear();
  }

  // ===========================================================================
  // PRIVATE METHODS
  // ===========================================================================

  /**
   * Check if a detection matches a recently alerted region.
   */
  private isDuplicate(detection: EsDetection): boolean {
    const now = Date.now();

    // Check against all recent alert regions
    for (const [key, timestamp] of this.lastAlertTimestamps.entries()) {
      // Clean up expired entries
      if (now - timestamp > DEDUP_WINDOW_MS) {
        this.lastAlertTimestamps.delete(key);
        continue;
      }

      // Parse the region key to get lat/lon
      const [latStr, lonStr] = key.split(",");
      const lat = parseFloat(latStr);
      const lon = parseFloat(lonStr);

      if (isNaN(lat) || isNaN(lon)) continue;

      // Check if the new detection is in the same region
      const distance = getDistance(
        lat,
        lon,
        detection.centerLat,
        detection.centerLon,
      );

      if (distance < SAME_REGION_THRESHOLD_KM) {
        return true;
      }
    }

    return false;
  }

  /**
   * Generate a region key from a detection for dedup tracking.
   * Rounds to 1 degree to group nearby detections.
   */
  private getRegionKey(detection: EsDetection): string {
    const lat = Math.round(detection.centerLat);
    const lon = Math.round(detection.centerLon);
    return `${lat},${lon}`;
  }

  /**
   * Auto-dismiss alerts older than AUTO_DISMISS_MS with no recent spots.
   */
  private autoDismissStale(): void {
    const now = Date.now();

    for (const alert of this.alerts) {
      if (alert.dismissed) continue;

      const timeSinceLastSpot = now - alert.detection.lastSpotAt;
      if (timeSinceLastSpot > AUTO_DISMISS_MS) {
        alert.dismissed = true;
      }
    }

    // Prune dismissed alerts older than 1 hour to prevent unbounded growth
    const ONE_HOUR_MS = 60 * 60 * 1000;
    this.alerts = this.alerts.filter(
      (a) => !a.dismissed || now - a.createdAt < ONE_HOUR_MS,
    );
  }
}

// =============================================================================
// SINGLETON INSTANCE
// =============================================================================

/** Default singleton instance for application-wide use */
let defaultInstance: EsAlertService | null = null;

/**
 * Get the default EsAlertService singleton.
 */
export function getEsAlertService(): EsAlertService {
  if (!defaultInstance) {
    defaultInstance = new EsAlertService();
  }
  return defaultInstance;
}
