/**
 * The ONE widget registry (plan §3). Data only: densities, whether a widget
 * can take the space, whether it transposes, its aspect, rail weight, phone
 * footprint, shared operating-state scope and bindings. No component
 * reference — pairing an id with its actual React implementation is a job
 * for the UI-layer PRs (#656+), which import both this registry and the
 * component tree.
 *
 * Seeded from:
 * - The 22 existing wall tiles, `src/components/map/hamclock/wall/tiles/index.ts`
 *   (`TileId`). Every id below that also appears in `TileId` is checked
 *   against it at the type level (`satisfies`), so a renamed or retired wall
 *   tile fails the build here, not silently.
 * - The Home dashboard widgets, `src/lib/home/layout.ts` (`HOME_LAYOUT_ITEMS`).
 * - Two new, additive families the plan calls for: the map hero (no wall
 *   tile — it is the wall's fixed background, never a picked widget) and the
 *   band x continent heat map (#632/#653/#654), which does not exist yet and
 *   is marked `status: "planned"` so recipes can still reference it.
 *
 * The "remaining wall tiles" the plan calls out as wall-only until a page
 * asks for more (§3) are: pskStation, wsjtx, sdrScope, sdrDecodes, muf,
 * reliability, emcomm. They also have no phone form (`phoneSize: "none"`)
 * until one is built.
 *
 * `wallInteractive` is omitted everywhere below and defaults to `false`
 * (`WidgetRegistryEntry.wallInteractive`): the wall is view-only today (a
 * click opens a report, `hamclock-wall-spec.md` §2) and no widget accepts
 * input there yet.
 */

import type { TileId } from "@/components/map/hamclock/wall/tiles";
import type { WidgetRegistryEntry } from "./types";

/** Registry ids that are also wall `TileId`s, checked at the type level. */
export const WALL_SEEDED_IDS = [
  "pskStation",
  "activations",
  "bestBand",
  "cluster",
  "bandActivity",
  "greyLine",
  "xray",
  "solarWind",
  "spaceWx",
  "sun",
  "weather",
  "moon",
  "forecastMatrix",
  "reliability",
  "muf",
  "alerts",
  "emcomm",
  "sdrScope",
  "wsjtx",
  "sdrDecodes",
  "recentContacts",
  "dxTarget",
] as const satisfies readonly TileId[];

/** Home dashboard widgets with no wall counterpart (`src/lib/home/layout.ts`). */
export const HOME_ONLY_IDS = [
  "activity",
  "forecast",
  "station",
  "daylight",
  "solar",
  "planets",
  "clocks",
  "countdowns",
  "tides",
  "environment",
  "scope",
  "metar",
  "volcanoes",
  "dxpeditions",
  "news",
  "contests",
  "history",
] as const;

const WALL_ONLY = ["wall"] as const;
const ALL_DENSITIES = ["wall", "glance", "work"] as const;

export const WIDGET_REGISTRY: Readonly<Record<string, WidgetRegistryEntry>> = {
  // -- Wall-seeded families --------------------------------------------
  pskStation: {
    id: "pskStation",
    title: "PSK Reporter",
    densities: WALL_ONLY,
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "none",
    scope: "global",
    bindings: [],
  },
  activations: {
    id: "activations",
    title: "Activations",
    densities: ["wall", "glance"],
    canSpace: false,
    transposable: false,
    aspect: "wide",
    weight: 1,
    phoneSize: "third",
    scope: "global",
    bindings: [],
  },
  bestBand: {
    id: "bestBand",
    title: "Best band now",
    densities: ALL_DENSITIES,
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "band",
    bindings: ["band"],
  },
  cluster: {
    id: "cluster",
    title: "DX cluster",
    densities: ALL_DENSITIES,
    canSpace: true,
    transposable: false,
    aspect: "tall",
    weight: 2,
    phoneSize: "full",
    scope: "band",
    bindings: ["band", "continent", "target", "spotId"],
  },
  bandActivity: {
    id: "bandActivity",
    title: "Band activity",
    densities: ALL_DENSITIES,
    canSpace: false,
    transposable: false,
    aspect: "wide",
    weight: 1,
    phoneSize: "half",
    scope: "band",
    bindings: ["band"],
  },
  greyLine: {
    id: "greyLine",
    title: "Grey line",
    densities: ALL_DENSITIES,
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "global",
    bindings: [],
  },
  xray: {
    id: "xray",
    title: "X-ray flux",
    densities: ALL_DENSITIES,
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "global",
    bindings: [],
  },
  solarWind: {
    id: "solarWind",
    title: "Solar wind",
    densities: ALL_DENSITIES,
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "global",
    bindings: [],
  },
  spaceWx: {
    id: "spaceWx",
    title: "Space weather",
    densities: ALL_DENSITIES,
    canSpace: false,
    transposable: false,
    aspect: "wide",
    weight: 1,
    phoneSize: "half",
    scope: "global",
    bindings: [],
  },
  sun: {
    id: "sun",
    title: "Sunrise / sunset",
    densities: ALL_DENSITIES,
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "global",
    bindings: [],
  },
  weather: {
    id: "weather",
    title: "Local weather",
    densities: ALL_DENSITIES,
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "global",
    bindings: [],
  },
  moon: {
    id: "moon",
    title: "Moon",
    densities: ALL_DENSITIES,
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "global",
    bindings: [],
  },
  forecastMatrix: {
    id: "forecastMatrix",
    title: "24h band forecast",
    densities: ALL_DENSITIES,
    canSpace: false,
    transposable: false,
    aspect: "wide",
    weight: 2,
    phoneSize: "half",
    scope: "band",
    bindings: ["band"],
  },
  reliability: {
    id: "reliability",
    title: "24h reliability",
    densities: WALL_ONLY,
    canSpace: false,
    transposable: false,
    aspect: "wide",
    weight: 1,
    phoneSize: "none",
    scope: "band",
    bindings: ["band"],
  },
  muf: {
    id: "muf",
    title: "MUF",
    densities: WALL_ONLY,
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "none",
    scope: "global",
    bindings: [],
  },
  alerts: {
    id: "alerts",
    title: "Weather alerts",
    densities: ALL_DENSITIES,
    canSpace: false,
    transposable: false,
    aspect: "wide",
    weight: 1,
    phoneSize: "half",
    scope: "global",
    bindings: [],
  },
  emcomm: {
    id: "emcomm",
    title: "Emcomm",
    densities: WALL_ONLY,
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "none",
    scope: "global",
    bindings: [],
  },
  wsjtx: {
    id: "wsjtx",
    title: "WSJT-X",
    densities: WALL_ONLY,
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "none",
    scope: "global",
    bindings: [],
  },
  sdrScope: {
    id: "sdrScope",
    title: "Band scope",
    densities: WALL_ONLY,
    canSpace: false,
    transposable: false,
    aspect: "wide",
    weight: 1,
    phoneSize: "none",
    scope: "band",
    bindings: ["band"],
  },
  sdrDecodes: {
    id: "sdrDecodes",
    title: "Decodes",
    densities: WALL_ONLY,
    canSpace: false,
    transposable: false,
    aspect: "wide",
    weight: 1,
    phoneSize: "none",
    scope: "global",
    bindings: [],
  },
  recentContacts: {
    id: "recentContacts",
    title: "Recent contacts",
    densities: ALL_DENSITIES,
    // The logger/fast-log family is the phone's page-1 widget on its own
    // (plan §6), so it must be able to take the space, not just a rail.
    canSpace: true,
    transposable: false,
    aspect: "wide",
    weight: 2,
    phoneSize: "full",
    scope: "session",
    bindings: ["sessionId", "band", "mode"],
  },
  dxTarget: {
    id: "dxTarget",
    title: "DX target",
    densities: ALL_DENSITIES,
    canSpace: false,
    transposable: false,
    aspect: "tall",
    weight: 2,
    phoneSize: "full",
    scope: "target",
    bindings: ["target", "spotId"],
  },

  // -- Additive families (no wall tile) --------------------------------
  mapHero: {
    id: "mapHero",
    title: "Map hero",
    // Full-bleed on the wall is fixed background, not a pickable widget
    // (see `WALL_SEEDED_IDS` note); no glance form exists for a map.
    densities: ["work"],
    canSpace: true,
    transposable: false,
    aspect: "any",
    weight: 3,
    // 2D flat has a phone form (`MobileMap.tsx`) but this family entry
    // covers 2D/3D/azimuthal together; the 3D globe form the owner named
    // as the "not on phone" example makes the family phone-unavailable
    // until the map hero splits by projection.
    phoneSize: "none",
    scope: "global",
    bindings: ["target", "band"],
  },
  heatMap: {
    id: "heatMap",
    title: "Band x continent heat map",
    densities: ALL_DENSITIES,
    canSpace: true,
    transposable: true,
    aspect: "wide",
    weight: 2,
    phoneSize: "full",
    scope: "band",
    bindings: ["band", "continent"],
    status: "planned",
  },

  // -- Home-only widgets (glance density, `src/lib/home/layout.ts`) ----
  activity: {
    id: "activity",
    title: "Bands now",
    densities: ["glance"],
    canSpace: false,
    transposable: false,
    aspect: "wide",
    weight: 1,
    phoneSize: "half",
    scope: "band",
    bindings: ["band"],
  },
  forecast: {
    id: "forecast",
    title: "Next 24 hours on your band",
    densities: ["glance"],
    canSpace: false,
    transposable: false,
    aspect: "wide",
    weight: 1,
    phoneSize: "half",
    scope: "band",
    bindings: ["band"],
  },
  station: {
    id: "station",
    title: "Your station & recent operating",
    densities: ["glance"],
    canSpace: false,
    transposable: false,
    aspect: "wide",
    weight: 2,
    phoneSize: "half",
    scope: "session",
    bindings: ["sessionId"],
  },
  daylight: {
    id: "daylight",
    title: "Daylight",
    densities: ["glance"],
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "global",
    bindings: [],
  },
  solar: {
    id: "solar",
    title: "Solar outlook",
    densities: ["glance"],
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "global",
    bindings: [],
  },
  planets: {
    id: "planets",
    title: "Planets",
    densities: ["glance"],
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "global",
    bindings: [],
  },
  clocks: {
    id: "clocks",
    title: "World clocks",
    densities: ["glance"],
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "global",
    bindings: [],
  },
  countdowns: {
    id: "countdowns",
    title: "Countdowns",
    densities: ["glance"],
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "session",
    bindings: [],
  },
  tides: {
    id: "tides",
    title: "Tides",
    densities: ["glance"],
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "global",
    bindings: [],
  },
  environment: {
    id: "environment",
    title: "UV & air quality",
    densities: ["glance"],
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "global",
    bindings: [],
  },
  metar: {
    id: "metar",
    title: "Aviation weather",
    densities: ["glance"],
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "global",
    bindings: [],
  },
  scope: {
    id: "scope",
    title: "QTH scope",
    densities: ["glance"],
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "global",
    bindings: [],
  },
  volcanoes: {
    id: "volcanoes",
    title: "Volcano watch",
    densities: ["glance"],
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "global",
    bindings: [],
  },
  dxpeditions: {
    id: "dxpeditions",
    title: "DXpeditions",
    densities: ["glance"],
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "global",
    bindings: [],
  },
  news: {
    id: "news",
    title: "Radio news",
    densities: ["glance"],
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "global",
    bindings: [],
  },
  contests: {
    id: "contests",
    title: "Contest details",
    densities: ["glance"],
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "global",
    bindings: [],
  },
  history: {
    id: "history",
    title: "This day in history",
    densities: ["glance"],
    canSpace: false,
    transposable: false,
    aspect: "square",
    weight: 1,
    phoneSize: "third",
    scope: "global",
    bindings: [],
  },
};

export function getRegistryEntry(id: string): WidgetRegistryEntry | undefined {
  return WIDGET_REGISTRY[id];
}
